### ISSUE TITLE
Set headers in moduleOptions

### ISSUE THREAD

**Issue by homerjam** [nuxt-community/axios-module#10]
The `setHeader` method is all very well but I'd prefer an option to simply pass a header in the module options - at the moment I'm using a separate plugin just to set one header. Feel free to point out where I'm going wrong here!

**Comment by pi0** [comment]
Hi @homerjam . You can use requestInterceptor option to modify headers too :)

**Comment by homerjam** [comment]
Ah yes! Ok that just what I need, thanks.
