### ISSUE TITLE
How to use '$axios.setHeader'

### ISSUE THREAD

**Issue by dengdan99** [nuxt-community/axios-module#100]
`$axios.setHeader('Content-Type', 'application/x-www-form-urlencoded', ['post'])`  
in plugins/axios.js , but do't work

![image](https://user-images.githubusercontent.com/6008719/35964681-64e0a972-0cf3-11e8-84f1-2a0a6f93facb.png)

**Comment by pi0** [comment]
Hey. I think this was because of how you are making request itself. Please also share the code you are currently using to make requests.

**Comment by awronski** [comment]
@pi0 I am not sure if it is related but for me ```$axios.setHeader``` wasn't working in the plugin.

What was working was:

```js
export default function ({ $axios, app, store }) {
  $axios.onRequest(config => {
    if (store.state.authToken) {
      config.headers.common['Authorization'] = store.state.authToken
    }
  })
}
```

The documentation isn't clear about it.

**Comment by awronski** [comment]
@dengdan99 In the pages I use axios like this:

```js
const config = {
    headers: { 'content-type': 'application/x-www-form-urlencoded' }
}

this.$axios.post(`/post/${id}`, model, config)
```

**Comment by dappiu** [comment]
If you want to use the helpers (setHeader, setToken, ...) provided by @nuxtjs/axios, you then must always use the request helpers provided by it, that are simply the lowercase http method names prefixed with a `$`

Stop doing `$axios.get( ... )` and do `$axios.$get( ... )`
and so on for put, post, delete, ...

And for setting Authorization header you can use the helper function setToken like that prefixes token with token type for you:
`this.$axios.setToken(userAccessToken, 'Bearer')` is equivalent to `this.$axios.setHeader('Authorization', ``Bearer ${userAccessToken}``)`

**Comment by datng14** [comment]
> @pi0 I am not sure if it is related but for me `$axios.setHeader` wasn't working in the plugin.
> 
> What was working was:
> 
> ```js
> export default function ({ $axios, app, store }) {
>   $axios.onRequest(config => {
>     if (store.state.authToken) {
>       config.headers.common['Authorization'] = store.state.authToken
>     }
>   })
> }
> ```
> 
> The documentation isn't clear about it.

You saved my day :)

**Comment by JuliusHamvie** [comment]
> > @pi0 I am not sure if it is related but for me `$axios.setHeader` wasn't working in the plugin.
> > What was working was:
> > ```js
> > export default function ({ $axios, app, store }) {
> >   $axios.onRequest(config => {
> >     if (store.state.authToken) {
> >       config.headers.common['Authorization'] = store.state.authToken
> >     }
> >   })
> > }
> > ```
> > 
> > 
> > The documentation isn't clear about it.
> 
> You saved my day :)



> @pi0 I am not sure if it is related but for me `$axios.setHeader` wasn't working in the plugin.
> 
> What was working was:
> 
> ```js
> export default function ({ $axios, app, store }) {
>   $axios.onRequest(config => {
>     if (store.state.authToken) {
>       config.headers.common['Authorization'] = store.state.authToken
>     }
>   })
> }
> ```
> 
> The documentation isn't clear about it.

Hi - Thank you very much for that. I have one questions: Where to place that code? I thought that I manipulate the Axios module in the nuxt.config.js file in the module section.

**Comment by awronski** [comment]
@JuliusHamvie 
in `plugins/axios.js`

**Comment by garan82** [comment]
@awronski , I add file plugins/axios.js , and in nuxt.config.js I added  

> plugins: ['~/plugins/axios.js']

In my page, I have
> import axios from 'axios'
> ...
>  return axios.get('/<some-path>').then(res => { return { data: res.<some-key> } })

but on server side I don't get authorization header. Do you know what I'm missing here?

**Comment by ram-you** [comment]
@garan82 
> import axios from 'axios'
...
return axios.get('/some-path').then(res => { return { data: res.some-key } })

1. Don't import axios, it's already defined in **this.$axios**
2. return **this.$axios**.get('/some-path').then(res => { return { data: res.some-key } })

**Comment by alucardu** [comment]
plugins/axios.js

```
  $axios.onRequest((config) => {
    config.headers.common['Content-Type'] = 'application/json'
```

nuxt config:

```
  plugins: [
    { mode: 'client', src: '~/plugins/axios' }
  ],
```

But the content type doesn't change:
![image](https://user-images.githubusercontent.com/779921/106970149-9468be80-674c-11eb-98d0-f4248b4f547c.png)

**Comment by eserdinyo** [comment]
I solved this issue for me this way.
create a new `axios.js` plugin
I created a new Axios instance

`const social = $axios.create({})`

set the base URL

`social.setBaseURL($config.socialApiURL)`

and inject it
```
inject('social', (url, method = 'GET', data = {}) =>
    social.request({
      method,
      headers: { 'content-type': 'application/json' },
      data: {},
      url,
   })
)
```

And I use it in my components;

```
async created() {
    const { data } = await this.$social('/users')
    console.log(data)
}
```
