### ISSUE TITLE
How to import module to external file

### ISSUE THREAD

**Issue by lukasborawski** [nuxt-community/axios-module#101]
So, let's say that I'm using axios module and extending it as a plugin. Now i need to import it to the external api.js file to define methods to fetch some data. 

**plugins/axios.js**
```
export default function ({ $axios, app, store, redirect, route }) {
  $axios.defaults.baseURL = process.env.baseUrl
  ...
```

**api/api.js**
```
import axios from '@nuxtjs/axios'

export default axios
```

and some api file

**api/feed.js**
```
import api from './api.js'

export default {
  getPosts (params) {
    return api.get
    ...
```

How to do this? Got undefined errors ... 

cc @pi0

**Comment by husayt** [comment]
I was just going to ask the same question

**Comment by lukasborawski** [comment]
@pi0 @Atinux @alexchopin can you guys help with this one?

**Comment by lukasborawski** [comment]
@husayt here you will find nice solution, tested, working.

https://github.com/nuxt-community/axios-module/issues/28

Closing.

**Comment by husayt** [comment]
@lukasborawski I think the following solution is far more elegant.

`/plugins/api.js`

```
const apiFactory = axios => ({
  getUsers(period = "Today") {
    return axios.get(`api/users`)
  },
  getProducts() {
    return axios.get(`/api2/products`)
  }
})

/*
** Executed by ~/.nuxt/index.js with context given
** This method can be asynchronous
*/
export default ({ $axios }, inject) => {
  // Inject `cookies` key
  // -> app.$api
  // -> this.$api in vue components
  // -> this.$api in store actions/mutations
  const api = apiFactory($axios)
  inject("api", api)
}

```
then use it like this
```
  async asyncData({ app }) {
    let { data } = await app.$api.getProducts()
...
  },
```

**Comment by husayt** [comment]
I also suggested this as an addition to axios module

**Comment by bovas85** [comment]
I'd recommend this above to be added with some config to avoid complexity

**Comment by husayt** [comment]
@bovas85 this in the plan. @pi0 is working on adding this to nuxt axios module. Will be really cool

**Comment by bovas85** [comment]
Great stuff :)

**Comment by tim-yao** [comment]
@husayt I couldn't make your code work, keep saying `Cannot read property 'getTest' of undefined`. `getTest` is my version of your `getProducts`. Do you know why?

**Comment by husayt** [comment]
I would need to see your code to say something.

**Comment by tim-yao** [comment]
It's a private repo, I am not able to share with you. But I used exactly same code as you posted. Thanks anyway @husayt 
However I used other work above around in https://github.com/nuxt-community/axios-module/issues/101#issuecomment-365657478 and it works for me.

**Comment by MerrySean** [comment]
Hi, I know that this thread is really old now. so yeah I'm wondering if this is still the best and most clean solution for this problem?

**Comment by husayt** [comment]
@MerrySean it still works for me too. I have seen some other approaches, but this is by far most simple and works like a brick.

**Comment by manniL** [comment]
I'm also using the same technique, described a bit more in detail in my [blog post](https://blog.lichter.io/posts/nuxt-api-call-organization-and-decoupling/)

**Comment by husayt** [comment]
Thanks @manniL, but isn't it now recommended to use nuxt http module instead of axios one?  From what I understand the latter is not going to be supported moving forward. Although, that doesn't change the main point of the article, still is good to know

**Comment by ubay1** [comment]
just import this in js file
`
import axios from 'axios/index';
`
