### ISSUE TITLE
translating docs

### ISSUE THREAD

**Issue by LuigiBaute** [nuxt-community/axios-module#103]
Hello, I am interested in collaborating with your project, serving as a translator to Spanish since it is my native language. I can translate any document (readme.md and changelod.md)

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c90">#c90</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi, @LuigiBaute Sorry for the late answer. Actually, we have now migrated docs to the gitbook so theoretically it is possible. I can make needed structural changes for this enhancement. Are you still interested?

**Comment by LuigiBaute** [comment]
Yes, @pi0 I'm still available :+1: let me know!
