### ISSUE TITLE
Should i put @nuxtjs/axios in nuxt.config.js build.vendor?

### ISSUE THREAD

**Issue by PhouvanhKCSV** [nuxt-community/axios-module#104]
Hi, 

Is it recommend to put `@nuxtjs/axios` in build vendor? like this

```javascript
...
build: {
    vendor: [
      '@nuxtjs/axios'
    ],
},
modules: [
    '@nuxtjs/axios'
 ],
...

**Comment by pi0** [comment]
Hi @PhouvanhKCSV. Both yes and no. I suggest only including `axios` in the `vendor` section if you want. Also, explicit vendor will not be needed anymore using nuxt 2.0.0 (upcoming version) webpack 4 will handle this automatically.
