### ISSUE TITLE
API factory pattern enabler

### ISSUE THREAD

**Issue by pi0** [nuxt-community/axios-module#106]
Implement according to discussions in #102.

Credits to this idea belongs to @husayt ❤️ 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c93">#c93</a>)</em></sub></div>

**Comment by linda8167** [comment]
How to use it ?

**Comment by tim-yao** [comment]
@pi0 will this be added soon?

**Comment by krystian50** [comment]
@pi0 any updates? I love the idea of a factory. 
In vanilla Vue project I usually use this pattern: https://medium.com/canariasjs/vue-api-calls-in-a-smart-way-8d521812c322 

I would like to use it with axios-module, but I can't find a nice approach to make API calls in external repository files without passing `this.$axios` instance as a function parameter. Normally I just import `repository.js` (I call it HttpService in my projects) file which exports axios instance. 

Do you know any way to get access to $axios property in non-vue files (outside of Vue context)?
This topic was discussed here many times, but I couldnt find any good solution.

**Comment by pi0** [comment]
@krystian50 Hi. You can create a plugin to inject the repository with axios instance.

`api/repository.js`:

```js
export default (axios) => ({
   method1: () => {}
})
```

`plugins/axios.js`:

```js
import repository from '~/api/repository'

export default function ({ axios }, inject) {    
   const api = repository(axios)
   inject('api', api)
}
```

Now `this.$api` would be available everywhere :)

**Comment by manniL** [comment]
Further read: https://blog.lichter.io/posts/organize-and-decouple-your-api-calls-in-nuxtjs ☺️ 	(shameless plug)

**Comment by krystian50** [comment]
@pi0 and @manniL thank you for your help :)

@manniL This article is amazing! That's exactly what I need! (it should be somewhere in official examples)

**Comment by LeCoupa** [comment]
@manniL Thank you for this article. It should be added to the nuxt axios documentation. :)

**Comment by manniL** [comment]
I'd probably close that issue as there are several packages implementing this pattern as mentioned in my article. Also this will help to keep the module simple and lean

**Comment by ricardogobbosouza** [comment]
@pi0 I think this can be closed
