### ISSUE TITLE
$axios.onError error has no data about the error

### ISSUE THREAD

**Issue by cayaner** [nuxt-community/axios-module#108]
appropriate your hard smart work, 

versions:
nuxt: 1.3.0
axios-module: 5.0.1

this is the JSON.stringify(error) for some of my responses, can't get the status code nor the response payload even it exists in dev tools network tab ..

```{
    "config": {
        "transformRequest": {},
        "transformResponse": {},
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Authorization": "Bearer ....."
        },
        "baseURL": "http://localhost:8000/",
        "method": "get",
        "url": "http://localhost:8000/v1/dash/...",
        "withCredentials": true
    },
    "request": {}
}

**Comment by pi0** [comment]
Hey and sorry for the late answer. Actually, axios error has some hidden keys including `error.request`, `error.response` and `error.config` which may be helpful for debugging better. Please reopen if your problem is not resolved.

**Comment by cayaner** [comment]
Thanks, Thanks For Your Efforts at All.

**Comment by javieerrubio11** [comment]
Thanks for that response. 

However, I think that you have to upgrade this section:

https://github.com/nuxt-community/axios-module/blob/master/docs/helpers.md

Because, the first example about **onError** not runs good, because error.code is undefined.

Thanks for all!
