### ISSUE TITLE
what's the `app` mean?

### ISSUE THREAD

**Issue by hello-guoguo** [nuxt-community/axios-module#109]
like this:
```
async asyncData({ app }) {
  const ip = await app.$axios.$get('http://icanhazip.com')
  return { ip }
}
```
## then what exactly does the `app` mean?

**Comment by BrianPurgert** [comment]
From [https://nuxtjs.org/api/context](url) (English Version)
KEY | TYPE | AVAILABLE | DESCRIPTION
-- | -- | -- | --
app | Root Vue Instance | Client & Server | The root Vue instance that includes all your plugins. For example, when using axios, you can get access to $axios through context.app.$axios.

This is actually a problem with NuxtJS doc translations not the axios-module

**Comment by hello-guoguo** [comment]
@BrianPurgert 
Yeah!
