### ISSUE TITLE
inject is not a function

### ISSUE THREAD

**Issue by tebaly** [nuxt-community/axios-module#11]
# npm run dev

```
  modules: [
    '@nuxtjs/axios',
  ],
```

Get Error

## inject is not a function

.nuxt/axios.js:133:2   (module.exports.__webpack_exports__.a)
.nuxt/index.js:115:51  ( _callee$)
internal/process/next_tick.js:188:7   (process._tickCallback)

---

  **axios.interceptors.response.use(undefined, errorHandler.bind(ctx));**

```
  // Inject axios to the context as $axios
  inject('axios', axios)

  // Setup axios helpers
  setupHelpers(axios)
}

module.exports.__webpack_exports__.a@133:2
```

---

How to fix?  

https://github.com/nuxt/nuxt.js/issues/1511#issuecomment-326402224

**Comment by pi0** [comment]
Hi. Please upgrade to nuxt rc8 for using axios module 4.0.0+ :)

**Comment by tebaly** [comment]
![image](https://user-images.githubusercontent.com/9466814/29946059-70c786cc-8eac-11e7-809a-8dcb07fc28a8.png)

Thank you!

**Comment by tebaly** [comment]
works

**Comment by falstack** [comment]
not work
