### ISSUE TITLE
baseURL doesnt work in nuxtServerInit

### ISSUE THREAD

**Issue by hackuun** [nuxt-community/axios-module#111]
I found out that it doesn't work

```js
export default {
  async nuxtServerInit({ commit }, { app }) {
    const response = await app.$axios.$get('topstories.json')
    const ids = response.data
    commit("SET_STORIES", ids)
  }
}
```

```js
modules: [
    '@nuxtjs/axios'
  ],
  axios: {
    baseURL: 'https://hacker-news.firebaseio.com/v0/'
  },
```

What is happening here?

**Comment by hackuun** [comment]
Wait the minute, this module not working entirely

```js

**Comment by paulgv** [comment]
Did you get any error message? What's the expected behaviour and what actually happens in your case? Can you provide a repo so the issue can be reproduced?

**Comment by qm3ster** [comment]
@hackuun do you even `console.log(ctx)`? -__-
They've put it on ctx and not app:
https://github.com/nuxt-community/axios-module/blob/fe169818f5eb6e6011330c1347594a77eb3f4485/lib/plugin.template.js#L176-L178

**Comment by pi0** [comment]
This is working as expected indeed. `$axios` is available in both `ctx` and `ctx.app`. The only reason it may not working might be outdated Nuxt.js version.

**Comment by qm3ster** [comment]
@pi0 why have it in multiple places?

**Comment by pi0** [comment]
@qm3ster Historically there was not any unified context for Nuxt.js. The correct way is inject/app only. But i think it is almost harmless to keep it in context too :)
