### ISSUE TITLE
Error. Division by zero

### ISSUE THREAD

**Issue by cawa-93** [nuxt-community/axios-module#116]
I understood the essence of this: if `config.progress === false`, then in this section of the code `currentRequests === 0`. What causes problems?

https://github.com/nuxt-community/axios-module/blob/1530bb67670f7bb06ce627f6783b6bcaa598eabc/lib/plugin.template.js#L139-L140
This leads to
```js
// await this.$axios.$get('/', {params, progress: false })
$loading().set(Infinity)
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c100">#c100</a>)</em></sub></div>

**Comment by cawa-93** [comment]
@pi0 It may be better not to perform this block at all if the `config.progress === false`

**Comment by sobolevn** [comment]
@pi0 this is resolved and can be closed ;)
