### ISSUE TITLE
Case insensitive proxyHeaders

### ISSUE THREAD

**Issue by mheppner** [nuxt-community/axios-module#12]
I apologize in advance if I'm missing something here, but when the frontend headers [get copied](https://github.com/nuxt-community/axios-module/blob/v4.0.0/lib/plugin.template.js#L119) into to the global headers, this is going to potentially have duplicate headers (`Accept` vs `accept`), right?

I noticed some of my requests on the Nuxt server side are being sent back from my Django API as HTML. After turning on debug, I see the headers as:
```
headers:
      { Accept: 'application/json, text/plain, */*',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        ...
```
I'm guessing the lowercase `accept` is the one being forwarded from the browser, but the capitalized `Accept` is the one I actually want.

Should there be a better way to merge in the headers from the incoming request? Or maybe just the accept header should be ignored?

**Comment by pi0** [comment]
Hi. Sorry for late response. Problem is now fixed by removing `accept` header.

**Comment by mheppner** [comment]
No problem, thank you :)
