### ISSUE TITLE
I want to request data in the store should be how to do

### ISSUE THREAD

**Issue by DestinyHunter** [nuxt-community/axios-module#123]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c104">#c104</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
https://axios.nuxtjs.org/usage#store-actions-including-nuxtserverinit

@manniL can close this?

**Comment by manniL** [comment]
Either as @ricardogobbosouza said or via `this.$axios` in the vuex actions.
