### ISSUE TITLE
How to cancel request when go to another route

### ISSUE THREAD

**Issue by kieusonlam** [nuxt-community/axios-module#125]
Is it possible to cancel the axios request that is not finish when user go to another route?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c105">#c105</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. Here is a cancel example: https://github.com/nuxt/hackernews/blob/master/store/index.js#L56

**Comment by asonnleitner** [comment]
@pi0 would there also be another way, instead of fetching all resource from a single action?
