### ISSUE TITLE
set headers is not working

### ISSUE THREAD

**Issue by krittanon-w** [nuxt-community/axios-module#127]
I'm trying to set header by using your init document and this code
```js
 this.$axios.setHeader('token', '123')
 this.$axios.get('/api/users/all').then((res) => {
    console.log('usersRes', res)
})
```
and

```js
headers = { token: '123'}
 this.$axios.get('/api/users/all',{headers}).then((res) => {
    console.log('usersRes', res)
})
```
but it not work. then I have inspected in chrome. this is result
<img width="445" alt="screen shot 2018-03-17 at 1 09 21 am" src="https://user-images.githubusercontent.com/18285224/37537654-d6413df8-2980-11e8-96df-83023892250e.png">
both of code is same result, token variable in header not set

**Comment by krittanon-w** [comment]
I use [axios set header not work](https://github.com/axios/axios/issues/891) to solve this problem and it can solve.

**Comment by dappiu** [comment]
Please read this comment
https://github.com/nuxt-community/axios-module/issues/100#issuecomment-473336105

You must use `$get()`, not `get()`
