### ISSUE TITLE
Response returns weird characters

### ISSUE THREAD

**Issue by johnRivs** [nuxt-community/axios-module#129]
I'm making a request to an external API. Everything works fine except `response.data` is returning something like this:
```
!�♥  ♠��        ▲,Zp→↔�<☼D#�.
�8�(N ☼hHs'>☼1�;�_↑►↕�♂↔^a�/�♀����D0�}♫ԥ>V►�↨�09�����4]♣ghn�q��◄�v�aޏ[�↕��G↑�i>my■�♂� sX�<♂�1ܛ~�O����V�8]↨-IT�_↑
```
- `nuxt 1.4.0`
- `@nuxtjs/axios ^5.1.1`

### nuxt.config.js
```js
module.exports = {
    modules: [
        '@nuxtjs/axios',
    ],

    axios: {
        baseURL: 'https://www.example.com/api',
        progress: true,
        credentials: true
    },
};
```

**Comment by johnRivs** [comment]
Turns out it has to do with the default value of the `accept-encoding` header. The server I'm making calls to is using the `br` value in the header.

**Comment by davemarceau** [comment]
Noting for others, John's solution works for the IGDB API if you had to skip "apicalypse" in your code (it uses axios behind the scenes anyway).

**Comment by Ripeplantain** [comment]
It doesnt work for me
