### ISSUE TITLE
AsyncData inside component

### ISSUE THREAD

**Issue by rAugustos** [nuxt-community/axios-module#13]
Hi!
In the`rc8` the function asyncData inside a component is not called according to README.md:

Component asyncData
```
async asyncData({ app }) {
console.log('Please call me')
}
```
`mode:spa`

Thanks in advanced

**Comment by mheppner** [comment]
I'm using rc8 and the latest axios-module and asyncData is working properly for me, in universal/non-SPA. Maybe report this over at the nuxt repo instead?

**Comment by pi0** [comment]
Hi. It works for me too. (Rc8 & RC9). Please reopen with a reproduction code.
