### ISSUE TITLE
Response interceptor using extend axios

### ISSUE THREAD

**Issue by kampfkuchen** [nuxt-community/axios-module#131]
I am trying to turn my working legacy code into code, which is going to work with version 5 and up.

Instead of using the response interceptor in the nuxt config file, I try to us it as an extension of axios in an axios plugin file. As recommended by [the updated documentation](https://axios.nuxtjs.org/extend.html).

My legacy code (in nuxt.config.js): 
```
axios: {
    responseInterceptor: (res) => {
       if (res.headers.authorization) {
           store.commit('auth/SET_TOKEN', res.headers.authorization)
       }
       return res
   }
}
```
I would be very thankful for any kind of help!

**Comment by pSchaub** [comment]
Just do it as described in your link. You just need to use `onResponse` instead of `onRequest`.
