### ISSUE TITLE
bug with store in asyncData() 

### ISSUE THREAD

**Issue by wlx200510** [nuxt-community/axios-module#133]
when I attempt get async data from server using store.$axios in asyncData()，I jump app.$axios because I use vuex actions to manage my data fetch API，but get error that store.$axios is undefined， can this be fixed?

**Comment by nikkanetiya** [comment]
Hello,

There is no store.$axios, if you need to fetch data inside store in actions use something like this

```
export const actions = {
  fetchData ({ commit }) {
    this.$axios.$get('') // fetch data
  }
}
```
