### ISSUE TITLE
how to use axios-module in service/getData.js？

### ISSUE THREAD

**Issue by se7en-1992** [nuxt-community/axios-module#135]
I want to know how to use axios-module in service/getData.js？

I want to manage interfaces in the same file.

I know to use app.$axios.$get/$post in the asyncData.

but,when i use axios-module in service/getData.js,

I have many problems.

please help me.

![1](https://user-images.githubusercontent.com/19768530/39353174-82f678f0-4a39-11e8-9fe3-bc11b0b11fa8.png)
![2](https://user-images.githubusercontent.com/19768530/39353179-84eb51f8-4a39-11e8-9bc7-df57725315c2.png)
![3](https://user-images.githubusercontent.com/19768530/39353183-86546f5c-4a39-11e8-9813-9818c6259fbe.png)

**Comment by se7en-1992** [comment]
![image](https://user-images.githubusercontent.com/19768530/39353305-cff2337e-4a39-11e8-9792-5b1cb9ed0d26.png)


I know to use app.$axios.$get/$post in the asyncData.
but I don't want to write every url of api in every file.
I want to manage api in the same file.

**Comment by se7en-1992** [comment]
@pi0

**Comment by Extarys** [comment]
Fellow NUXT users, this is a duplicate of [c120](https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c120). Please go there to share and help. Thanks :smile_cat:
