### ISSUE TITLE
How to use axios-module in service/getData.js

### ISSUE THREAD

**Issue by se7en-1992** [nuxt-community/axios-module#136]
I want to know how to use axios-module in service/getData.js？

I want to manage interfaces in the same file.

I know to use app.$axios.$get/$post in the asyncData.

but,when i use axios-module in service/getData.js,

I have many problems.

please help me.
![image](https://user-images.githubusercontent.com/19768530/39354025-eec6e4c8-4a3b-11e8-8dc5-9e79df61884e.png)
![image](https://user-images.githubusercontent.com/19768530/39354036-f43182b0-4a3b-11e8-9f4d-3626300701dc.png)
![image](https://user-images.githubusercontent.com/19768530/39354044-fa6fa864-4a3b-11e8-9c9d-e8b952c63e3f.png)

I know to use app.$axios.$get/$post in the asyncData.
but I don't want to write every url of api in every file.
I want to manage api in the same file.

![image](https://user-images.githubusercontent.com/19768530/39354067-0abdc3f4-4a3c-11e8-9db6-fa46ce66bb53.png)

**Comment by se7en-1992** [comment]
I can use the following method to solve, 
But I have an another question.

![1.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/81129fa0-4a84-11e8-b49c-eb1dfb18787e.png)
![2.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/85555260-4a84-11e8-b49c-eb1dfb18787e.png)



When I click on the browser's history back button, the error has showed.

![3.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/d2598220-4a84-11e8-b49c-eb1dfb18787e.png)

**Comment by se7en-1992** [comment]
@pi0

**Comment by se7en-1992** [comment]
Refresh is ok, only history-back is error

**Comment by Extarys** [comment]
Acccess-control is triggered because axios is reaching another domain than the one were the page was served. You need to tell the remote server (api endpoint) to accept request from your local machine. (Even if both are on localhost, note that changing the port will trigger access-origin error)

[Cross-Origin Resource Sharing (CORS) - MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

[Cors middleware on NPMJS](https://www.npmjs.com/search?q=cors)

To make sure check the header you receive from your api:
![cors.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/866ad150-4a95-11e8-aa03-39cb3bfcf116.png)


Hope it helped.

**Comment by se7en-1992** [comment]
@Extarys i have setted the proxy to link the remote sever

**Comment by Extarys** [comment]
Hmm, did you add your file as a plugin? I found [this](https://axios.nuxtjs.org/extend.html)

plugins/axios.js:
```
export default function ({ $axios, redirect }) {
  $axios.onRequest(config => {
    console.log('Making request to ' + config.url)
  })

  $axios.onError(error => {
    const code = parseInt(error.response && error.response.status)
    if (code === 400) {
      redirect('/400')
    }
  })
}
```

nuxt.config.js
```
plugins: [
    '~/plugins/axios'
  ]
```

**Comment by se7en-1992** [comment]
@Extarys 
![E1ED16C2-0E59-4E74-949E-0BAFF4B8B285.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/fb210940-4a9c-11e8-aa03-39cb3bfcf116.png)

**Comment by se7en-1992** [comment]
plugins/axios.js:
![1897AAAF-9DAA-4818-848C-65627AF178B2.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/31760860-4a9d-11e8-8818-0b933b2fefc0.png)

**Comment by Extarys** [comment]
Refer to my previous post, you don't include axios and you need to export a function.

Cheers

**Comment by Extarys** [comment]
Your code is in services/getData, so you need to include it in your plugins.

**Comment by se7en-1992** [comment]
when i open the project in the browser, it is ok! but,when i click the history.go(-1),the error has showed --------'Access-Control-Allow-Origin'

**Comment by se7en-1992** [comment]
@Extarys 
nuxt.config.js:

```js
modules: [
    '@nuxtjs/axios'
  ],
  axios: {
    proxy: true,
    prefix: '/api'
    // See https://github.com/nuxt-community/axios-module#options
  },
  proxy: {
    '/api': {
      target: (process.env.NODE_ENV === 'production') ? production.porductionProxy : production.developmentProxy,
      pathRewrite: { '^/api': '' }
    }
  },
  plugins: [
    '@/plugins/mint-ui',
    '@/plugins/axios',
    '@/plugins/veeValidate',
    {
      src: '~/plugins/vux/vux-plugins',
      ssr: false
    },
    {
      src: '~/plugins/vux/vux-components',
      ssr: true
    }
  ]
```

plugins/axios.js:
```js
export default function ({ $axios, redirect }) {
  $axios.onRequest(config => {
    if (config.method === 'post') {
      if (!config.data) return
      // node 不支持URLSearchParams
      // var params = new URLSearchParams()
      var params = ''
      Object.keys(config.data).forEach(key => {
        // params.append(key, config.data[key])
        params += key + '=' + config.data[key] + '&'
      })
      Object.defineProperty(config, 'data', {
        value: params
      })
    }
    console.log('Making request to ' + config.url)
  })

  $axios.onError(error => {
    const code = parseInt(error.response && error.response.status)
    if (code === 400) {
      redirect('/400')
    }
    if (error.code === 500) {
      redirect('/error')
    }
  })
}
```


index.vue
```js
async asyncData ({ app }) {
    function getBannerList() {
      return app.$axios.$get(`/index/articleList.html?nid=app_banner`)
    }
    function getArticleList() {
      return app.$axios.$get(`/crowdfunding/articleIndex.html`)
    }
    function getProjectList() {
      return app.$axios.$get(`/wx/crowdfunding/index.html`)
    }
    function getNewsList() {
      return app.$axios.$get(`/abouts/news/newsListPage.html?page=1&pagesize=3`)
    }
    // Parallel requests
    try {
      const [ bannerData, articleData, projectData, newsData ] = await Promise.all([getBannerList(), getArticleList(), getProjectList(), getNewsList()])
      ........
    } catch (e) {
     .......
    }

  }
```

**Comment by se7en-1992** [comment]
One week ago, my project was still working.when i click the back button is also normal.
but,today,It has an error

**Comment by se7en-1992** [comment]
@Extarys hi,my friend，please help me what is the reason for this?

**Comment by Extarys** [comment]
What was the other file you had getData.js? can you post it too please? I just want to make sure it's not in the code, I tried something similar and it seems to work.

**Comment by se7en-1992** [comment]
@Extarys the getData.js file,i have not imported.
![2B21DF12-2E9A-4A9B-A0B9-234D8BA1E2A8.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/911a0f20-4aaa-11e8-8818-0b933b2fefc0.png)

you click this button,your console of the browser has not error?

**Comment by se7en-1992** [comment]
![qw.gif](https://cmty.s3.eu-west-1.amazonaws.com/100171714/91f80bb0-4aad-11e8-b55d-75625dc928db.gif)
@Extarys

**Comment by Extarys** [comment]
Could you check make sure the API call made when the error is produced actually return something and that the header is correct?

**Comment by Extarys** [comment]
Sorry noticed it was in the gif.
It looks like it doesn't return anything.
1) Check why those calls are made and remove them/fix them
2) Make sure they are supposed to return something
3) Configure CORS

I don't really know. Maybe someone today will be able to help you.
