### ISSUE TITLE
Default value of proxyHeadersIgnore should include content-* headers

### ISSUE THREAD

**Issue by masterada** [nuxt-community/axios-module#139]
### What problem does this feature solve?

1. setup axios + proxy module
2. post to the site from outside (not as an ajax request, just a regular post)
3. during the handling of the post, send a get request to the api (eg: to fetch logged in user data for ssr)
4. axios proxy uses the original content-length header, resulting in a timeout as the server waits for request body

### What does the proposed changes look like?

default value for proxyHeadersIgnore should be: ['host', 'accept', 'content-type', 'content-length', 'content-md5']

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c124">#c124</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@pi0 Does it make sense to add by default 'content-type', 'content-md5'?

**Comment by pi0** [comment]
This issue should be already resolved by [v5.5.4](https://github.com/nuxt-community/axios-module/releases/tag/v5.5.4). Sorry for not updating issue (i think a similar issue was created in nuxt repo)

BTW i think it makes sense to remove `content-md5` and `content-type` as well.
