### ISSUE TITLE
handle set-cookie for CSRF-TOKEN

### ISSUE THREAD

**Issue by falstack** [nuxt-community/axios-module#14]
``` javascript
reqMethods.forEach(method => {
  axiosExtraProto['$' + method] = function () {
    return this[method].apply(this, arguments).then(res => {
      if (isServer) { // set-cookie can't auto write cookie on SSR
        const csrfKey = this.options['csrfKey'];
        if (csrfKey) {
          const csrfToken = parseCookie(res.headers['set-cookie'], this.option['csrfKey'])
          this.setHeader(csrfKey, csrfToken)
        }
      }
      return res && res.data
    })
  }
})
```

**Comment by pi0** [comment]
Hi. Why not using `setHeader` helper instead?

`this.$axios.setHeader('set-cookie', csrfKey)`

**Comment by falstack** [comment]
The reason for the following:
1: this.$axios.$methods only return data without headers, I can not handle the header
2: If I do this, I have to handle the header in every await of asyncData, so there will be a lot of duplication

But I found that the header did not set up successfully
``` javascript
reqMethods.forEach(method => {
  axiosExtraProto['$' + method] = function () {
    return this[method].apply(this, arguments).then(res => {
      if (res.headers['set-cookie']) {
        const data = res.headers['set-cookie'][0].split('=');
        this.setHeader(data[0], data[1].split(';')[0])
        this.setHeader('foo', 'bar')
        console.log(this.defaults.headers);  // print foo: bar and csrf-token, not in request
      }
      return res && res.data
    })
  }
})
```

**Comment by falstack** [comment]
How can i send(extends) server side axios headers to client axios headers?

**Comment by pi0** [comment]
Hi again and sorry for response delay. A new `init` option is now added to module options. I still don't get the exact usage but i think it may be helpful for this issue.

**Comment by falstack** [comment]
Thank you very much, you never need to say sorry, but this should be a Nuxt question, look here:
https://github.com/nuxt/nuxt.js/issues/1590
