### ISSUE TITLE
http://axios.nuxtjs.org/ not work

### ISSUE THREAD

**Issue by pasBone** [nuxt-community/axios-module#141]
both http://axios.nuxtjs.org  and https://axios.nuxtjs.org not work.  The number of times you redirect you too much.

**Comment by pasBone** [comment]
why

**Comment by TakahiRoyte** [comment]
https://nuxtjs.cmty.io/nuxt-community/axios-module/issues/c128
I just posted this as a bug.  It seems like SSL certification is outdated.

**Comment by Atinux** [comment]
Fixed, thanks
