### ISSUE TITLE
How to handle error in plugin?

### ISSUE THREAD

**Issue by Bombay** [nuxt-community/axios-module#149]
Hi. How to handle error in plugin?

```
export default function ({ $axios, store, error }) {
  $axios
    .onError(apiError => {
      error({statusCode: '403', message: 'test'})
    })
}
```

![image](https://user-images.githubusercontent.com/9034302/41975666-568e557e-7a56-11e8-8a75-71bdbfe0e1e8.png)

redirect is working. but error is not work.
thank you for great module.

**Comment by odanado** [comment]
I got the same issue. But I found a solution to the issue.
When I return `false` in `interceptors.request.use`, I can cancel the request. (https://github.com/axios/axios/issues/583)

Therefore, I return `Promise.resolve(false)` in `onError`.

```javascript
export default function ({ $axios, store, error }) {
  $axios
    .onError(apiError => {
      error({statusCode: '403', message: 'test'})
      return Promise.resolve(false);
    })
}
```
