### ISSUE TITLE
can't use responseInterceptor

### ISSUE THREAD

**Issue by cayaner** [nuxt-community/axios-module#15]
i'm trying to set a global response interceptor, 

```
responseInterceptor: (response, {
        store
      }) => {
        if (response.data.message) {
          store.dispatch('toast', response.data, {
            root: true
          })
        }
        return response
      }
```
i'm getting this error, 

![screenshot from 2017-09-04 00-50-39](https://user-images.githubusercontent.com/19613212/30006869-2e3253e4-910b-11e7-8870-cd87a8c38ebd.png)

how can i do it correctly ?

**Comment by pi0** [comment]
Hi. I've added a responseInterceptor test and is just passing. I think the problem would be outside the scope of this module. Please reopen if is there any problem with axios-module or you have a reproduction code.

**Comment by cayaner** [comment]
Thank you,
You are right ..
I moved the condition  if (response.data.message)  to the action method and it works great.

I don't know why but it's ok for now.
