### ISSUE TITLE
Authorization header doesn't exist

### ISSUE THREAD

**Issue by kindles** [nuxt-community/axios-module#151]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://gist.github.com/kindles/d89233807efa0a5090eb36e7536bed62](https://gist.github.com/kindles/d89233807efa0a5090eb36e7536bed62)

### Steps to reproduce

Use the module in asyncData() and mounted(), in the first method It works (the request has an header authorization) and in the second method It doesn't work (the request doesn't have an header authorization).

### What is expected ?

this.$axios.defaults.headers.common['Authorization'] = accessToken; and this.$axios.setHeader('Authorization', '123') set a header when I use the module in a mounted function.

### What is actually happening?

this.$axios.defaults.headers.common['Authorization'] = accessToken; and this.$axios.setHeader('Authorization', '123') doesn't set an header when I use the module in a mounted function.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c142">#c142</a>)</em></sub></div>

**Comment by kindles** [comment]
https://github.com/nuxt-community/axios-module/issues/130

I just found that ... still not resolved.

**Comment by Atinux** [comment]
Hi @kindles 

You need to set the token on client-side too, an example is to use a plugin that you add into your `nuxt.config.js`: 

```js
module.exports = {
  plugins: ['~/plugins/auth.js']
}
```

Then in `plugins/auth.js`: 

```js
export default async (ctx) => {
  const { store, app } = ctx

  // Check if user is connected
  if (process.server) {
    await store.dispatch('auth/checkConnectedUser', ctx)
  }
  // Set token to axios
  if (store.state.auth.jwt) {
    app.$axios.setToken(store.state.auth.token)
  }
}
```

And in `store/auth.js`: 

```js
var cookieparser = require('cookieparser');

// ... state...

export const actions = {
  checkConnectedUser ({ commit }, { req }) {
    let accessToken = null
    if (req.headers.cookie) {
      var parsed = cookieparser.parse(req.headers.cookie)
      if (parsed.auth) {
        accessToken = parsed.auth;
        this.$axios.setToken(accessToken);
        // TODO: Add token to state.token

        return this.$axios.$get('/account/info').then(resp => {
          let user = resp.data;
          user.token = accessToken;
          commit('user/SET_USER', user);
        })
      }
    }
  }

```
