### ISSUE TITLE
Axios with nuxt property decorator Always Send OPTIONS method

### ISSUE THREAD

**Issue by Try-Parser** [nuxt-community/axios-module#159]
when i send POST method it always send OPTIONS why it is ? i already tried alot of things like 

```
      proxyHeaders: false,
      credentials: false 
```
```

> 
> OPTIONS /app/security/login-processing HTTP/1.1
> Host: localhost:8080
> Connection: keep-alive
> Pragma: no-cache
> Cache-Control: no-cache
> Access-Control-Request-Method: POST
> Origin: http://localhost:3000
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-US,en;q=0.9
> 


```
@pi0

**Comment by Try-Parser** [comment]
@pi0

**Comment by francoislevesque** [comment]
Same thing for me... Unable to make a POST request to the slack API.
```
this.$axios.$post('https://hooks.slack.com/services/...', JSON.stringify(data))
.then(response => {
   //
})
.catch(error => {
   //
})
```

The method is always OPTIONS instead of POST

**Comment by pi0** [comment]
Hi. Sorry, I was not able to respond fast. Actually, this is browser that makes **Two requests** One Options for [preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) and secondly the real request.  If you have CORS problems with slack I would recommend enabling proxy mode.

```js
{
  axios: { proxy: true },
  proxy: {
    '/services': 'https://hooks.slack.com/services/`
  }
```

Then simply making requests to the same domain:

```js
this.$axios.$post('/services/...', data)
```

**Comment by gomezmark** [comment]
hi @Try-Parser 

How did you solve this problem?
Thanks

**Comment by Try-Parser** [comment]
@gomezmark it is usually sending two request The first is OPTIONS to test and if the first request is successfull then it will send the second request its actually it is the behavior of the cors preflight so you need to add the OPTIONS or Support some HTTP verbs in your API and if your using some custom headers you need to add those also in your global cors in server side

**Comment by gomezmark** [comment]
@Try-Parser 
Great thanks!
But it only occurs on IE and Mozilla.
Anyways, it is now working on my end.
Thanks!

**Comment by Try-Parser** [comment]
@gomezmark happy to help

**Comment by dpmccabe** [comment]
I had this exact same problem with a route on my API that end with `links`. I don't know why, but every API route I tried that ended with `links` would send the OPTIONS request. Changing the route to end with `linkz` (or anything else) fixed the problem. I don't know if this was a problem with Nuxt, Axios, or my API.

**Comment by MDeeee** [comment]
I fix this by adding 
`axios: {
		baseURL: process.env.API_URL,
		proxy: true
	},
	proxy: {
		'/api/': process.env.API_URL,
	},`
to nuxt.config.js file
