### ISSUE TITLE
Possible CORS error, Postman Calls work to API but Store-> Actions-> Axios Calls to LOGIN do not work BCRYPT compare password fails.

### ISSUE THREAD

**Issue by tonysworking** [nuxt-community/axios-module#165]
This is a general NUXT question.

I am making an axios request to login a user, I can sign-up a user with no errors, but when i try to login, that newly made user with axios  does not work, I get a 401 error 

If i use postman to Create a user and Log in that same user It works perfectly.

If i use postman to login the user created with Axios it gives a 401 error.

is nuxt sending a different type of data to the server because I am converting a vueJS app to a nuxtApp and the VUEJS app works perfectly as well.

the API is its own app and runs on an entirely different port (2030) and has nothing todo with the Nuxt application, it has CORS set up in the app

app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header('Access-Control-Allow-Headers', "Origin, X-Requested-With, Content-Type, Accept, Authorization");
    if (req.method === 'OPTIONS') {
        res.header('Access-Control-Allow-Methods', 'PUT, POST, PATCH, DELETE, GET');
 
        return res.status(200).json({});
    }
    next();
});

  

the failed code is as such:

API LOGIN

USER LOGIN
router.post('/login', (req, res, next) => {
    console.log('request');
    User.findOne({
            email: req.body.email
        })
        .exec()
 
        .then(user => {
            if (user.length < 1) {
                return res.status(401).json({
                    message: 'Authorization Failed'
                });
            }
            
        bcrypt.compare(req.body.password, user.password, (err, result) => {
 
                if (err) {
                    return res.status(401).json({
                        message: err,
                    });
                }
 
                if (result) {
                    const token = jwt.sign({
                            email: user.email,
                            userId: user._id,
                        },
                        process.env.JWT_KEY, {
                            expiresIn: '1h'
                        });
                    return res.status(200).json({
                        message: user,
                        token: token
                    });
                }
                res.status(401).json({
                    message: err,
                });
            });
 
        })
        .catch(err => {
            console.log(err);
            res.status(500).json({
                error: err
            });
        });
})

The Nuxt Store Action:

login({
        commit,
        state
      }, authData) {
        axios
          .post("http://127.0.0.1:2030/users/login", {
            email: authData.email,
            password: authData.password,
            returnSecureToken: true
          })
          .then(res => {
            commit("authUser", {
              token: res.data.token
            });
            state.userIncorrectLogin = "";
            router.push("/dashboard");
          })
          .catch(error => {
            state.userIncorrectLogin =
              "Email Or Password is Incorrect Please try again or Reset Password";
          });
      },

The login.vue Methods:

methods: {
    submit(email, password) {
      this.$validator.validateAll();
      if (!this.errors.any()) {
        this.$store.dispatch("login", { email, password });
      }
    },

Any thoughts or recommendations on this issue.

Thanks in Advance.

**Comment by filipkisic** [comment]
You should format all code as a code to be more readable.
It is not said what you use for your API, but I had similar issue with calls to my node.js server where I have API. I solved it by installing [cors](https://www.npmjs.com/package/cors) . You just install it with npm, import and add app.use(cors()) . As I read, it has to do with what headers are read and defined on your server and expected, this way it is read as if you weren't using cors but sending from a different source.  I didn't set up any special options, just added it and it worked fine for my usecase
