### ISSUE TITLE
onError - Not Returning Error Code

### ISSUE THREAD

**Issue by altafsayani** [nuxt-community/axios-module#169]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://codesandbox.io/](https://codesandbox.io/)

### Steps to reproduce

I am trying to use onError helper as mentioned in documentation (https://axios.nuxtjs.org/helpers) But it is not returning error code. It is simply just returning string message "Network Error"

### What is expected ?

Should return error object with status code and status message.

### What is actually happening?

Only returning generic error message.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c176">#c176</a>)</em></sub></div>

**Comment by LeCoupa** [comment]
I get the same issue.

**Comment by NielsSteensma** [comment]
Same issue here. 

So I did some quick googling and realized Axios returns 'Network error' when it didn't get a response from the web service it made the request to. In my case it was related to a CORS issue on my API. After solving that issue the onError helper works fine.
See also: https://github.com/axios/axios/issues/383

Summarized; this is not a bug, just the way Axios handles errors without responses.

**Comment by ricardogobbosouza** [comment]
@pi0 can closed?
