### ISSUE TITLE
Please remove /plugins/axios.js dependency.

### ISSUE THREAD

**Issue by lyquocnam** [nuxt-community/axios-module#17]
Hi author, i see currently this module require `~/plugins/axios.js` as dependency,
can you make this module standalone ?
i think we can config in `nuxt.config.js` is fine !

**Comment by pi0** [comment]
Hi. But this module without plugin would not be useful! Would you please explain your use case without plugin?

**Comment by lyquocnam** [comment]
can we include this to module too ?

```javascript
import * as axios from 'axios'

let options = {}
// The server-side needs a full url to works
if (process.server) {
  options.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
}

export default axios.create(options)
```

**Comment by pi0** [comment]
No we can't. Modules run in Nuxt **build lifecycle** not runtime. Also inside plugins export default is not possible as we should avoid write stateful code in global context as of Vue 2.3.x (Because requests are shared)

**Comment by pi0** [comment]
Please see https://ssr.vuejs.org/en/api.html#runinnewcontext

**Comment by lyquocnam** [comment]
ok i see, thanks for you answer @pi0 i just felt lazy to add more plugin when have added module...
