### ISSUE TITLE
Don't accept br encoding on Server side

### ISSUE THREAD

**Issue by manniL** [nuxt-community/axios-module#170]
### What problem does this feature solve?

Node can't parse brotli natively. Browser can.

That's why axios on server-side will throw up with gibberish characters when it retrieves content from a brotli API.

We should set the appropriate headers to avoid that behavior by default.

Example: https://codesandbox.io/s/m4k3yn7x8

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c180">#c180</a>)</em></sub></div>

**Comment by jericopulvera** [comment]
@manniL did you solved this?

**Comment by manniL** [comment]
@jericopulvera Check the CSB ;)
