### ISSUE TITLE
attempting to refresh my token

### ISSUE THREAD

**Issue by acidjazz** [nuxt-community/axios-module#18]
Upon a token_expired when I check `/me` for authorization, or any route that requires authorization, I need to hit `/refresh` to attempt to refresh my token, i gave it a shot using the `errorHandler` like so:

```js
  axios: {
    errorHandler (error) {
      if (error.response.data && error.response.data.error === 'token_expired') {
        console.log ('expired token, going after /refresh')
        this.$axios.get('/refresh').then((res) => {
          error.config.__isRetryRequest = true
          return this.$axios(error.config)
        })
      }
    }
  },
```

But I had no luck since `this.$axios` is undefined, any other way I can do this?

**Comment by pi0** [comment]
Hi. It should be available now. Please upgrade to `v4.1.0`.
