### ISSUE TITLE
I can't perform penument.resolve in the error blocker, which will cause the app direct crash

### ISSUE THREAD

**Issue by zhaojunlike** [nuxt-community/axios-module#183]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://github.com/nuxt-community/axios-module/tree/dev/lib](https://github.com/nuxt-community/axios-module/tree/dev/lib)

### Steps to reproduce

I can't perform penument.resolve in the error blocker, which will cause the app direct crash;

 hello，I want an axios interceptor like onError to return custom data after execution, but this can cause the program to crash
![image](https://user-images.githubusercontent.com/13638996/48880527-e1059f00-ee4b-11e8-8ce7-5c483ccea577.png)
```
   $axios.onError((error) => {
        const code = parseInt(error.response && error.response.status);
        const message = (error.response && error.response.data && error.response.data.message) || 'Api请求失败';
        console.error("Api:", error.message, message);
        switch (code) {
            case 500:
                break;
            default:
                break;
        }
        const res = {message: message, ok: false, status: code};
        return res;
    });
```

### What is expected ?

When working directly with axios, this is fine.Because our back-end encapsulates the data differently, we identify success by ok

### What is actually happening?

app crashed

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c190">#c190</a>)</em></sub></div>

**Comment by zhaojunlike** [comment]
I've solved this problem, and it's not an exception brought on by axios

**Comment by manniL** [comment]
@zhaojunlike more info please :relaxed:

**Comment by zhaojunlike** [comment]
Sorry, I thought that the crash was caused by the return value of axios at first, but later I found that the nuxt tag was used in the error page template of nuxt, which would directly cause the app crash

**Comment by zhaojunlike** [comment]
This problem can be closed
