### ISSUE TITLE
Should proxyHeaders and credentials be true by default?

### ISSUE THREAD

**Issue by homerjam** [nuxt-community/axios-module#20]
Just questioning whether these two useful features should be `true` by default - I found they caused problems with my setup. As a noob or someone switching from the regular `axios` module they introduce implicit complexity which can take a while to debug (vs. time saved from the benefits).

At lease a note regarding `proxyHeaders`:

> If directing requests at a url protected by CloudFlare's CDN you should set this to `false` to prevent CloudFlare from mistakenly detecting a reverse proxy loop and returning a 403 error.

**Comment by pi0** [comment]
Thanks. I've added the not. Actually, it depends on the use case but i think should be enabled by default to make it having a universal behavior. If you know some unwanted headers that CF adds that makes problems, just open a PR or ping me :)

**Comment by homerjam** [comment]
Well I think it's `cf-ray` header as described [here](https://support.cloudflare.com/hc/en-us/articles/200171976-Error-1000-DNS-points-to-prohibited-IP), I'll check when I can (assuming I can use an interceptor to remove it).

**Comment by CurtisBelt** [comment]
@pi0 

> If you know some unwanted headers that CF adds that makes problems, just open a PR or ping me

I believe I have that answer for you. To avoid [Error 1000: DNS points to prohibited IP](https://support.cloudflare.com/hc/en-us/articles/200171976-Error-1000-DNS-points-to-prohibited-IP) that @homerjam  is referencing, I used `proxyHeadersIgnore` to remove the headers `cf-ray` and `cf-connecting-ip`.


nuxt.config.js
```
modules: [
  '@nuxtjs/axios'
],
axios: {
  proxyHeadersIgnore: ['host', 'accept', 'cf-ray', 'cf-connecting-ip']
},
```

**Comment by tiagomatosweb** [comment]
Hi all, 
I'm getting the same issue. I've tried proxyHeaders = true which is true by default and I also have tried proxyHeadersIgnore: ['host', 'accept', 'cf-ray', 'cf-connecting-ip'] and did not work. I'm getting the Error 1000: DNS points to prohibited IP.

Any idea?

**Comment by jucau** [comment]
Hello all,

maybe it will help someone, I had same kind of trouble with Cloudfront, getting a 403 when using a cookie based auth API with `proxyHeaders: true`. 
Solution was to ignore also Cloudfront headers in `proxyHeadersIgnore` : `['host', 'accept', 'cf-ray', 'cf-connecting-ip', 'content-length', 'via', 'user-agent', 'cloudfront-forwarded-proto', 'cloudfront-is-desktop-viewer', 'cloudfront-is-mobile-viewer', 'cloudfront-is-smarttv-viewer', 'cloudfront-is-tablet-viewer', 'cloudfront-viewer-country', 'x-amz-cf-id', 'x-amzn-trace-id', 'x-forwarded-for', 'x-apigateway-event', 'x-apigateway-context']`.
Not sure all the above headers are necessary to ignore to get it work, but in my case I didn't need them and it solved my issue.
