### ISSUE TITLE
Bearer token on SSR

### ISSUE THREAD

**Issue by manniL** [nuxt-community/axios-module#202]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://github.com/nuxt-community/modules/issues/89](https://github.com/nuxt-community/modules/issues/89)

### Steps to reproduce

See https://github.com/nuxt-community/modules/issues/89

### What is expected ?

-

### What is actually happening?

-

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c206">#c206</a>)</em></sub></div>

**Comment by SHxKM** [comment]
Any progress regarding this? I can't seem to use a global interceptor to set my token based on state (in nuxt config)

**Comment by ricardogobbosouza** [comment]
@manniL Is there currently a problem with this?

**Comment by ricardogobbosouza** [comment]
@pi0 Is there currently a problem with this?

**Comment by pi0** [comment]
the issue already transferred to #298
