### ISSUE TITLE
How to set axios.defaults.xxx?

### ISSUE THREAD

**Issue by DaxChen** [nuxt-community/axios-module#21]
Hi,
Thanks for the great module!

How do I set global defaults to all axios requests? 
For example:

```js
axios.defaults.xsrfHeaderName = 'X-CSRF-TOKEN'
```

Thanks!!!

**Comment by pi0** [comment]
Hi. `init` option support added please upgrade to `v4.1.0` & check the docs. (BTW `'X-CSRF-TOKEN'` is already default in axios so not needed to specify)

**Comment by DaxChen** [comment]
WOW! That was super fast!!!
Tried v4.1.1 and works great!
Thank you so much!!!
(BTW the default is `X-XSRF-TOKEN`, but I saw you implemented some tests so you must already found out XD)
