### ISSUE TITLE
Canceling a request doesn't respect 'progress' option

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-community/axios-module#211]
### Version

[5.3.1](https://github.com/axios-module/releases/tag/5.3.1)

### Reproduction link

[https://codesandbox.io/s/kmojxplqz5](https://codesandbox.io/s/kmojxplqz5)

### Steps to reproduce

See https://codesandbox.io/s/kmojxplqz5 - cancel a request using a cancel token once the request has started with the progress option as false.

### What is expected ?

No progress bar to show

### What is actually happening?

The 'failed' progress bar shows

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c211">#c211</a>)</em></sub></div>

**Comment by miecio1212** [comment]
@pi0 it'll be fixed?

**Comment by miecio1212** [comment]
I tried to make pull request but I don't know why I can't push my branch to repo so here is solution
in lib/plugin.js add check if error isCancel
```
  axios.onError(error => {
    if (error && error.config && error.config.progress === false) {
      return
    }
    if (axios.isCancel(error)) {
      return
    }

    currentRequests--
    $loading().fail()
    $loading().finish()
  })
```

**Comment by mv92** [comment]
as a workaround, if you already import axios to get cancel token, you can use axios.get instead of this.$axios.get since you don't want the progress in the first place;
