### ISSUE TITLE
asyncData with params

### ISSUE THREAD

**Issue by jamestowers** [nuxt-community/axios-module#22]
How can i access the `app` variable when using the params in asyncData? eg:

```
async asyncData ({ params, app?? }) {
  let { data } = await app.$axios.$get(`/admin/pages/${params.id}`)
  return { page: data }
}
```

the above doesnt work

**Comment by pi0** [comment]
‍‍‍‍‍‍```js
async asyncData ({ params, app?? }) {
  const page = await app.$axios.$get(`/admin/pages/${params.id}`)
  return { page }
}
```

This will work. Notice the magic of `$get` instead of `get`. Which automatically extracts data part for an easier and _fetch_ style usage syntax.

**Comment by jamestowers** [comment]
Yep, you're right, not sure what i did wrong.

Thanks
