### ISSUE TITLE
How to use $axios in another plugin

### ISSUE THREAD

**Issue by kaboume** [nuxt-community/axios-module#226]
Hi,
I read that $axios can be used in a custom plugin but I don't know how to do it ?
Have you got an example ? 
Thanks in advance

**Comment by StephanKroukamp** [comment]
Wondering the same thing.
Please let me know if you find out.

**Comment by manniL** [comment]
Further read: https://blog.lichter.io/posts/organize-and-decouple-your-api-calls-in-nuxtjs/

**Comment by StephanKroukamp** [comment]
> Further read: https://blog.lichter.io/posts/organize-and-decouple-your-api-calls-in-nuxtjs/

Hi thank you for the post. learned alot of new stuff and definitely usefull. im still struggling to access the repository in another plugin file for nuxt. i cannot get anything working and not one actual example...
