### ISSUE TITLE
In plugin, when setting token stored in vuex, axios reads valid string as null

### ISSUE THREAD

**Issue by xhw994** [nuxt-community/axios-module#228]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://jsfiddle.net/hrg94qye/](https://jsfiddle.net/hrg94qye/)

### Steps to reproduce

With only nuxt and nuxt/axios, I added the code shown in JSFiddle to plugin/axios.js.
Although I can log the correct value from the console, $axios.setToken and $axios.setHeader ig

### What is expected ?

axios adds the correct authorization header value:
'Authorization': 'Bearer ${token}'

### What is actually happening?

setToken will do nothing unless passing in an explicit string value
setHeader will add 'Authorization': 'Bearer '

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c216">#c216</a>)</em></sub></div>

**Comment by xhw994** [comment]
My thoughts:
It is likely that onRequest only register the code once to axios. The following-up requests do not update the behavior. Even if I do the following it won't work:

`if (store.getters.isAuthenticated) {
      console.log(store.getters.jwtToken);
      $axios.setToken(store.getters.jwtToken, 'Bearer', ['post', 'put', 'delete']);
    }`

Then, where should I register this behavior globally?

**Comment by pi0** [comment]
setToken should be called directly in plugin not with onRequest. During onRequest defaults (+the ones set by setToken) are already applied.

If token is variable based on request (Which is unlikely to be use case) it is possible to update req object with onRequest interceptor.

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/64949796-92c6fe00-d8ac-11e9-9054-c3a3eeaaae4a.png)

**Comment by ricardogobbosouza** [comment]
Similar https://github.com/nuxt-community/axios-module/issues/130#issuecomment-544915944

@pi0  can closed?
