### ISSUE TITLE
this.$axios not working in store action in rc9

### ISSUE THREAD

**Issue by jamestowers** [nuxt-community/axios-module#23]
This doesn't seem to be working with the latest tag
```
{
  actions: {
    async getIP ({ commit }) {
      const ip = await this.$axios.$get('http://icanhazip.com')
      commit('SET_IP', ip)
    }
  }
}
```

if i revert to 

`import axios from '~/plugins/axios'`

```
{
  actions: {
    async getIP ({ commit }) {
      const ip = await axios.get('http://icanhazip.com')
      commit('SET_IP', ip)
    }
  }
}
```

then it works again

**Comment by mheppner** [comment]
I can confirm it is still working as expected in rc9.

Can you ensure your Vuex is updated to 2.4?

**Comment by jamestowers** [comment]
Yes, Vuex 2.4

It might be because i'm chaining store actions from `nuxtServerInit()` in `index.js` ?

index.js:
```
export const actions = {
  async nuxtServerInit ({dispatch}, { req }) {
    return Promise.all([
      dispatch('categories/fetch'),
      dispatch('settings/fetch')
    ])
  }
}
```

categories.js:
```
export const actions = {
  async fetch ({ commit }) {
    let { data } = await this.$axios.$get('/admin/categories')
    commit('load', data)
  }
}
```

**Comment by mheppner** [comment]
At least for me, even using `nuxtServerInit()` and `dispatch()`ing other methods, it still works as expected.

**Comment by jamestowers** [comment]
Yeah it's working now, I'm not sure what the problem was but I expect it wasn't related to this module.

Thanks for you help @mheppner

**Comment by mheppner** [comment]
@jamestowers no problem, I didn't really help though lol. When in doubt, just remove node_modules and install your dependencies again.
