### ISSUE TITLE
New issue URL is broken

### ISSUE THREAD

**Issue by rothskeller** [nuxt-community/axios-module#230]
Your issue template says to submit issues through https://nuxtjs.cmty.io/issues/new, but that URL doesn't exist.

**Comment by rothskeller** [comment]
Mentioning @pi0 per instructions above.

**Comment by manniL** [comment]
@rothskeller Resolved https://github.com/nuxt-community/axios-module/commit/624a3bd2c14f6e598c35f6716576b18dbc9a500c
