### ISSUE TITLE
Bad issue tracking link

### ISSUE THREAD

**Issue by rothskeller** [nuxt-community/axios-module#231]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[http://not-applicable](http://not-applicable)

### Steps to reproduce

Go to https://github.com/nuxt-community/axios-module/issues/new.

### What is expected ?

Issue submission template gives URL where new issue can be submitted.

### What is actually happening?

Issue submission template gives a broken URL.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c219">#c219</a>)</em></sub></div>

**Comment by manniL** [comment]
Already fixed by the latest commit
