### ISSUE TITLE
context.route is not updated

### ISSUE THREAD

**Issue by sdr0x07b6** [nuxt-community/axios-module#236]
### Version

[v5.4.1](https://github.com/axios-module/releases/tag/v5.4.1)

### Reproduction link

[https://github.com/sdr0x07b6/route.git](https://github.com/sdr0x07b6/route.git)

### Steps to reproduce

`git clone git@github.com:sdr0x07b6/route.git`
`cd route && yarn && yarn dev`

Transition while looking at Developer Tools console.

### What is expected ?

Just as route is updated in `asyncData`, it should be updated in interrupts as well.

### What is actually happening?

The route changes normally in `asyncData()` of each page every time the page transits.
However, the interrupted request does not change route regardless of where it is transitioned.
It does not change from the route at the time of SSR.

Access to `/`
  `console.log(route)` --> `{ path: 'index', ... }`

Next, transition `/users`
  `console.log(route)` --> `{ path: 'index', ... }` // Not updated

Next, transition `/products`
  `console.log(route)` --> `{ path: 'index', ... }` // Not updated

And, `from` is always `undefined`.

### Additional comments?

Access to Index:
[in asyncData]        route.path:/ from.path:null
[in $axios.onRequest] route.path:/ from.path:null

Next, transition to Users:
[in asyncData]        route.path:/users from.path:/
[in $axios.onRequest] route.path:/ from.path:null

Next, transition to Products:
[in asyncData]        route.path:/products from.path:/users
[in $axios.onRequest] route.path:/ from.path:null

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c223">#c223</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. This issue is not related to the axios module. I think the problem with the plugin is that param extraction from context means we always keep the initial reference (thus not updating). Something like this should work:

```js
export default function (ctx) {
  ctx.$axios.onRequest(config => {

    console.log('[in $axios.onRequest]',
      'route.path:', ctx.route.path,
      'from.path:', ctx.from ? ctx.from.path : null)

    return config
  })
}
```
