### ISSUE TITLE
Globally capture errors

### ISSUE THREAD

**Issue by derpdead** [nuxt-community/axios-module#241]
### Version

[v5.1.0](https://github.com/axios-module/releases/tag/v5.1.0)

### Reproduction link

[https://axios.nuxtjs.org/extend](https://axios.nuxtjs.org/extend)

### Steps to reproduce

Follow setting axios from nuxt documentary.

### What is expected ?

Whenever we catch the error inside `$axios.onError` we should redirect to the given route. I could handle the error on each request by catching it, but as far as we got global handler we should be able to catch it in one place.

### What is actually happening?

It is throwing NuxtServerError.

     [Axios] Response error: Request failed with status code 401                                                                                                                                                         
     09:59:32

     at createError (node_modules/axios/lib/core/createError.js:16:15)
     at settle (node_modules/axios/lib/core/settle.js:18:12)
     at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:201:11)
     at IncomingMessage.emit (events.js:202:15)
     at IncomingMessage.EventEmitter.emit (domain.js:481:20)
     at endReadableNT (_stream_readable.js:1132:12)
     at processTicksAndRejections (internal/process/next_tick.js:76:17)

### Additional comments?

I would like to add my code to describe more precisely situation:

I have registered axios module and extended it:
    
    plugins: [
        '~plugins/axios',
    ],

    modules: [
        '@nuxtjs/axios',
    ],

The plugin:

    const EXPIRED_TOKEN_MESSAGE = 'Expired JWT Token';
    
    export default function ({
        $axios, redirect, app, store,
    }) {
        $axios.setHeader('Content-Type', 'application/json');
        $axios.setHeader('Accept', 'application/json');
    
        $axios.onRequest((config) => {
            console.log(`Making request to ${config.url}`);
        });
        
        $axios.onError((error) => {
            const { response: { data: { message } } } = error;
    
            if (message === EXPIRED_TOKEN_MESSAGE) {
                store.dispatch('authentication/logout');
            }
    
            store.dispatch('alerts/addAlert', { type: 'error', message });
        });
    }

The store: 

    logout({ commit }) {
        Cookie.remove('jwt');
        commit('setUser', null);
        commit('data/clearStorage', {}, { root: true });

        this.$router.push({ name: 'index' });
    },

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c235">#c235</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. You have to handle the error. Maybe returning an empty object at the end of `onError` handler.

**Comment by derpdead** [comment]
@pi0 Hello, thank you for fast response. Even when you return Promise.reject(error); it will not work. Could we get update of the docs in extending axios section with working example when the error occurs ?

**Comment by pi0** [comment]
It works as expected. `Promise.reject` means also throwing an error (promise chain). 

```js
    $axios.onError((error) => {
        const { response: { data: { message } } } = error;

        if (message === EXPIRED_TOKEN_MESSAGE) {
            store.dispatch('authentication/logout');
        }

        store.dispatch('alerts/addAlert', { type: 'error', message });

        return false
    });
```

As this is a global handler, you have to check response when using.

```js
async asyncData({ $axios }) {
   const res = $axios.$get('...')
   if (!res) { 
      // An error occured
   }
}

**Comment by derpdead** [comment]
Thank you for explanation, I though that you could handle everything in global handler as the name is pointing 'onError'.

**Comment by pi0** [comment]
True. But the result of `$get`/`get` function should be finally an error or some value. Not returning or returning undefined from interceptor means we just intercepted error for example for logging stuff.

**Comment by derpdead** [comment]
I did as you say. Update slightly my code by adding `catch(e => console.log(e))` to the request and next error occurred in node_modules/@nuxt/devalue/dist/devalue.cjs.js 

RangeError
Maximum call stack size exceeded

**Comment by pi0** [comment]
You are returning entire error object in `asyncData` result. Can you please share full code of `asyncData` and newly changed `onError`?

**Comment by derpdead** [comment]
I found where the problem is: 

Steps: 
- error occurred 
- JWT Token expired
- Cleared all data from store / cookies
- redirected
- nuxtServerInit is called
- checking for token - it should be removed but it is not.

        $axios.onError((error) => {
            const { response: { data: { message } } } = error;
    
            if (message === EXPIRED_TOKEN_MESSAGE) {
                store.dispatch('authentication/logout');
                redirect('/');
            }
    
            store.dispatch('alerts/addAlert', { type: 'error', message });
        });
    
        logout({ commit }) {
            Cookie.remove('jwt');
            commit('setUser', null);
            commit('data/clearStorage', {}, { root: true });
        },

        async nuxtServerInit({ commit, dispatch }, { req, app }) {
            let token = null;
            if (req.headers.cookie) {
                const parsed = cookieparser.parse(req.headers.cookie);
                if (parsed.jwt) {
                    token = parsed.jwt;
                    app.$axios.setHeader('JWTAuthorization', `Bearer ${token}`);
                    await dispatch('authentication/getUser');
                }
            }
        },

        async getUser({ commit }) {
            await this.app.$axios.$get('profile').then((user) => {
                commit('setUser', user);
                this.$router.push({ name: 'dashboard' });
            }).catch(e => console.log(e));
        },

**Comment by SHxKM** [comment]
@derpdead - did you find a good solution for this? I'm experiencing similar behaviour.

**Comment by patra12** [comment]
✔ Server
  Compiled successfully in 15.07s

ℹ Waiting for file changes                                                                            17:33:36

 READY  Server listening on http://localhost:3000                                                     17:33:36

(node:3861) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/kus3/Desktop/Heroku/nuxt-auth-kus/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/kus3/Desktop/Heroku/nuxt-auth-kus/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/kus3/Desktop/Heroku/nuxt-auth-kus/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:3861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3861) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/kus3/Desktop/Heroku/nuxt-auth-kus/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/kus3/Desktop/Heroku/nuxt-auth-kus/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/kus3/Desktop/Heroku/nuxt-auth-kus/node_modules/axios/lib/adapters/http.js:237:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:3861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
/*--------------------------------------------------------------------------------------------------------*/

every thing is fine .and project is running but still
this error is coming in console in nuxt js

**Comment by indigoram89** [comment]
I have the same
<img width="601" alt="Снимок экрана 2020-01-24 в 12 55 10" src="https://user-images.githubusercontent.com/10687211/73060413-d22fd780-3ea8-11ea-8dcf-0b4318261d74.png">

**Comment by alex-eri** [comment]
I find a way to disable nuxt interceptors

Works with  

```
$axios.onError((error) => {
    return true
  })
```

**Comment by jessielaf** [comment]
I find it tedious to have a `.catch(console.log)` after each request. I do even more every time a request fails. But I still get sent to the error page of Axios. Is there any way to prevent this?

I tried the `return true` or `return false` at the end of my onError interceptor.

This is what my interceptor looks like
```
  $axios.onError(error => {
    const code = parseInt(error.response && error.response.status)

    if (code === 401 || code === 403) {
      store.dispatch('logout')
    } else {
      store.dispatch('snackbar/error')
    }
  })
```

**Comment by pi0** [comment]
While it is not really recommended to globally suppress errors what you can do is:

```js
export default function ({ $axios }) {
  $axios.onError((error) => {
    return { error, data: {} }
  })
}
```

It will cause if `$axios` requests failing, return an empty object for data and `error` is available in reponse object but nothing throws anymore.

**Comment by BudiSalah** [comment]
@pi0 
> Hi. You have to handle the error. Maybe returning an empty object at the end of `onError` handler.

Can you explain more why returning empty object fix the issue!
