### ISSUE TITLE
impossible to use @nuxtjs/axios in nuxt.config.js for the generate route method

### ISSUE THREAD

**Issue by darkylmnx** [nuxt-community/axios-module#242]
### What problem does this feature solve?

Today if I want to generate routes I have to use the seperate axios npm package which is not consistent since I have to duplicate the baseURL.
Also, I created an API class that uses the instance of @nuxtjs/axios, if I use a seperate instance of axios, I can't use my service anymore as the regular axios does not have all the methods included in @nuxtjs/axios

What I currently do:

nuxt.config.js

```javascript

const api = 'https://myapi'

import axios from 'axios'

export default {
  modules: ['@nuxtjs/axios'],

    axios: {
      baseURL: api
    },

  generate: {
    routes() {
      return axios.get(api + '/collection').then(res => {
        return res.data.map(one => ('my-route/' + one.id))
      })
    }
}
```

### What does the proposed changes look like?

What i'd like to do:

nuxt.config.js

```javascript
export default {
  modules: ['@nuxtjs/axios'],

    axios: {
      baseURL:  'https://myapi' // no need to keep this in two places anymore
    },

  generate: {
    routes({ $axios }) {
      return $axios.$get('/collection').then(data => {
        return data.map(one => ('my-route/' + one.id))
      })

      // OR with my service that I could add to $axios, which internally use
      $axios.API = require('@/services/API')
      $axios.API.init($axios)

      return $axios.API.getMappedCollection()
    }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c236">#c236</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @darkylmnx 

Sadly it's a bit harder than it looks like since the `nuxt.config.js` is not handled by Webpack compared to the whole Vue app.

But good news, we are working on an internal crawler so you won't have to specify `generate.routes` anymore 😄

**Comment by darkylmnx** [comment]
Can't wait to see that then.

For now I had to do code duplication, it's not optimal and I guess I'll
have maintaining issues later but it works for now.

Le mer. 22 mai 2019 à 00:34, Sébastien Chopin <notifications@github.com> a
écrit :

**Comment by manniL** [comment]
Anyway, I'd love to see that feature as it can come in handy for e.g. feed generation (via https://github.com/nuxt-community/feed-module) too. If the crawled routes can be used there too, it'd be :+1:

**Comment by ricardogobbosouza** [comment]
This is not a problem with this module.
Unfortunately we cannot use module intances in `nuxt.config.js`
@pi0 can closed?

**Comment by ihorbond** [comment]
I ended up installing axios as dev dependency. works fine

**Comment by klukiyan** [comment]
> I ended up installing axios as dev dependency. works fine


@ihorbond 
Can you please show how did you make it?
how your nuxt.config looks like?
Thank you
