### ISSUE TITLE
double bearers in authorization field in 5.5.0 for nuxt/Auth

### ISSUE THREAD

**Issue by WtekSupport** [nuxt-community/axios-module#250]
### Version

[v5.5.0](https://github.com/axios-module/releases/tag/v5.5.0)

### Reproduction link

[https://codepen.io](https://codepen.io)

### Steps to reproduce

  axios: {
    baseURL: process.env.API_ENDPOINT,
    withCredentials: true
  },

/////

  auth: {
    redirect: {
      login: '/login/',
      logout: '/',
      callback: '/login/',
      home: '/control/'
    },
    resetOnError: true,
    fullPathRedirect: true,
    rewriteRedirects: true,
    strategies: {
      password_grant: {
        _scheme: 'local',
        endpoints: {
          login: {
            url: 'api/v1/oauth/token/',
            method: 'post',
            propertyName: 'access_token'
          },
          logout: false,
          user: {
            url: 'api/v1/account/me/',
            method: 'get'
          }
        }
      },

      'laravel.passport': {
        url: process.env.API_ENDPOINT,
        client_id: process.env.PASSPORT_CLIENT_ID,
        client_secret: process.env.PASSPORT_CLIENT_SECRET
      }
    }
  },

### What is expected ?

Getting a token
getting user data

### What is actually happening?

got token - ok
for getting user data sending 
authorization: Bearer ...... , Bearer .......
...
got 401

for version 5.4.1 - no any problem

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c249">#c249</a>)</em></sub></div>

**Comment by dappiu** [comment]
I can confirm the same behaviour, also tried in changing the default tokenName for local strategy to lowercase 'authorization', but the issue stays (btw I noticed that every header sent with the request is Camel-Cased except for 'authorization' that now is all lowercase)

**Comment by proaleks94** [comment]
+

**Comment by multiart** [comment]
same problem too

**Comment by alexis-loumeau** [comment]
i can confirme too

**Comment by pi0** [comment]
Sorry for inconveniences. It is probably related to 2e514a4. Will investigate more.

**Comment by pi0** [comment]
fixed in @nuxtjs/axios@5.5.1
