### ISSUE TITLE
Setting defaults with SSR

### ISSUE THREAD

**Issue by kirillbunin** [nuxt-community/axios-module#256]
### Version

[v5.5.3](https://github.com/axios-module/releases/tag/v5.5.3)

### Reproduction link

[*](*)

### Steps to reproduce

I have following in my nuxt.config.js:
```
  modules: [
    '@nuxtjs/axios',
  ],
  axios: {
    debug: process.env.NODE_ENV !== 'production',
    baseURL: process.env.NODE_ENV === 'production' ? 'https://production/api/' : 'https://staging/api/',
    browserBaseURL: process.env.NODE_ENV === 'production' ? 'https://production/api/' : 'https://staging/api/',
    credentials: true,
    proxyHeaders: true,
    init (axios, ctx) {
      axios.defaults.xsrfHeaderName = 'X-CSRF-TOKEN'
    }
  },
```

### What is expected ?

To change the default `xsrfHeaderName` to `X-CSRF-TOKEN`

### What is actually happening?

When I make requests on my API's, I get error `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://staging/api/transaction?_format=json. (Reason: missing token ‘x-xsrf-token’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).`
(Notice the xsrf, not csrf)

### Additional comments?

If I create a `nuxt-client-init.js `with:
```
export default ({ app }) => {
 app.$axios.defaults.xsrfHeaderName = 'X-CSRF-TOKEN'
}
```

and in my `nuxt.config.js` I put
```
  plugins: [
    { src: '~/plugins/nuxt-client-init.js', ssr: false },
  ],
```

It works as expected.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c253">#c253</a>)</em></sub></div>

**Comment by ozakha** [comment]
Actually, I came across on the same issue.
I also use `vue-mc` lib, and expect to set `baseURL`, `headers` globally, and, set Authorization token via `intercepters.request` for both: integrated $axios and for axios in models/collections.
I used nuxt plugin and tried do it in 3 ways: 
1) via `axios.defaults`
2) via interceptor of origin `axios`
3) via helper of integrated `$axios` onRequest (which is the sugar method for 2))
And, unfortunately, no success.

**Comment by MicroDreamIT** [comment]
I am having same issue.

**Comment by ricardogobbosouza** [comment]
Hi @kirillbunin 
I think this `init` option does not exist, is not documented anywhere
Try this:

```js
// nuxt.config.js
export default {
  ...
  axios: {
    ...
    xsrfHeaderName: 'X-CSRF-TOKEN'
  }
  ...
}
```

**Comment by pi0** [comment]
1. @ricardogobbosouza I'm not sure we support `xsrfHeaderName` name.
2. The default value for `xsrfHeaderName` option in axios is already `'X-CSRF-TOKEN'` there is no need to provide it again! See [docs](https://github.com/axios/axios#request-config)
3. For using a custom (other than `X-CSRF-TOKEN`) header name, see [extend](https://axios.nuxtjs.org/extend) section. 

plugins/axios.js
```js
export default function ({ $axios }) {
    $axios.defaults.xsrfHeaderName = 'SOMETHING-ELSE'
}
```

**Comment by ricardogobbosouza** [comment]
@pi0 The default value for `xsrfHeaderName` option in axios is `X-XSRF-TOKEN` not `X-CSRF-TOKEN`

**Comment by pi0** [comment]
@ricardogobbosouza Ah now I see. Maybe we can add an option as you proposed if it has a common usage?

**Comment by ricardogobbosouza** [comment]
Now we can customize the headers directly through nuxt.config.js https://github.com/nuxt-community/axios-module/pull/294 that's enough

**Comment by ricardogobbosouza** [comment]
@pio I see no need, if necessary the user create a plugin as you mentioned https://github.com/nuxt-community/axios-module/issues/256#issuecomment-544729304
