### ISSUE TITLE
Refreshing pages and returning data formats via routing jumps are different

### ISSUE THREAD

**Issue by cdwmhcc** [nuxt-community/axios-module#257]
### Version

[v5.5.3](https://github.com/axios-module/releases/tag/v5.5.3)

### Reproduction link

[https://zh.nuxtjs.org/](https://zh.nuxtjs.org/)

### Steps to reproduce

async asyncData({ app, params, error, payload }) {
      const list = await app.context.app.$axios.$get('/api/items/soft',{
        params:{
          status: "published"
        }
      })
      return {
        post: data.data[0]
      }
    },

刷新页面返回数据一切正常：

   {
        data: [{
          id: 1,
          title:'Hello World'
        }]
        meta: {
          result_count: 1
        }
 }

![1.jpg](https://cmty.s3.eu-west-1.amazonaws.com/100171714/044bc1d0-8783-11e9-bbfe-0f66363c2ba5.jpg)

通过路由跳转返回的数据：

{
    id: 1,
    title:'Hello World'
}

![2.jpg](https://cmty.s3.eu-west-1.amazonaws.com/100171714/2335ba60-8783-11e9-bbfe-0f66363c2ba5.jpg)

meta不见了

### What is expected ?

数据返回一致

### What is actually happening?

我有一篇文章，它的url是xxxx.com/blog/helloworld
我直接通过url访问，数据是正常的，
但是当我通过<NuxtLink :to="'/blog/helloworld‘">Hello World</NuxtLink>访问的时候，返回的数据就不正常了，具体的可以我上传的图片

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c254">#c254</a>)</em></sub></div>

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/58953148-2e35d680-87c8-11e9-92b8-6f48a24b1446.png)

**Comment by pi0** [comment]
Hi. Can you please explain in english? Also a reproduction in codesandbox can help.

**Comment by cdwmhcc** [comment]
> Hi. Can you please explain in english? Also a reproduction in codesandbox can help.

I have an article, URL is xxxx.com/blog/helloworld
I access it directly through url, and the data returned is normal.
But when I access it through <NuxtLink:to="'/blog/helloworld'">Hello World </NuxtLink>, the data returned is abnormal. Specific pictures can be uploaded by me.

**Comment by pi0** [comment]
Iss your issue resolved?
