### ISSUE TITLE
progress: false does not work in version 5.5.3

### ISSUE THREAD

**Issue by karambafe** [nuxt-community/axios-module#258]
### Version

[v5.5.3](https://github.com/axios-module/releases/tag/v5.5.3)

### Reproduction link

[https://codesandbox.io/s/8n6z6z30j8](https://codesandbox.io/s/8n6z6z30j8)

### Steps to reproduce

Add progress: false in request config:
```
this.$axios.get('URL', { progress: false });
this.$axios.post('URL', { data: 'data' }, { progress: false });
```

### What is expected ?

progress bar is not displayed 

### What is actually happening?

Progress bar displayed for all types of requests (get, post, patch, delete)

### Additional comments?

in version 5.3.6 it works correctly

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c255">#c255</a>)</em></sub></div>

**Comment by levemsan** [comment]
It worked just fine until v5.5.2; I think there's a problem on axios 0.19.0.

**Comment by delanoflipse** [comment]
I did some digging and found that this might indeed be the result of an update in axios. But more in the sense that it shouldn't have worked in earlier versions of this module.

When doing any axios request, axios creates a generic config file to create a request (see: https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js)

It does **not** include the `progress` key. The axios onRequest hook that this module uses (see: https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.js, line 108), expects that it does.

Creating a plugin as such:
```js
$axios.onRequest(config => {
  console.log(config.progress);
});
```
Shows that it is always `undefined` (as could be expected), so the test `config && config.progress === false` always fails.

I was unable to find a way to pass custom data to the axios config as of yet.
For now this ugly fix worked:
```js
// https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.js, line 108
axios.onRequest(config => {
  if (config && config.progress === false) {
    return;
  }

  if (config && config.headers && config.headers.__show_no_progress__ === true) {
    delete config.headers.__show_no_progress__;
    return;
  }

  currentRequests++;
});

// works with
$axios.$post(url, payload, { headers: { __show_no_progress__: true } });
```

**Comment by eol3** [comment]
I use v5.5.4 have same question.
And use v5.5.2 work fine.

**Comment by yariksav** [comment]
This behaviour is because axios prepare it's config data with function **mergeConfig** only with own properties, and skip unfamiliar properties

https://github.com/axios/axios/blob/405fe690f93264d591b7a64d006314e2222c8727/lib/core/mergeConfig.js#L13-L50

Now { progress: false } doen't work never

**Comment by daniluk4000** [comment]
Still not working in 5.6.0

**Comment by libeocom** [comment]
Hi,
I think this is related, the progress bar is reset for each request.
Instead of getting a single progress bar for all the request in asyncData,
the progress bar is reset for each request (using await) which is not ideal and very ugly.
I created an `.onRequest` interceptor to disable (`progress: false`) globally and now it works like intended.

**Comment by mrleblanc101** [comment]
Hi,
I think this is related, the progress bar is reset for each request.
Instead of getting a single progress bar for all the request in asyncData,
the progress bar is reset for each request (using await) which is not ideal and very ugly.
I created an .onRequest interceptor to disable (progress: false) globally and now it works like intended.

**Comment by daniluk4000** [comment]
Does your solution work for single requests? If so, can you please share an example of solution so we can use it?

**Comment by mrleblanc101** [comment]
In a plugin
```
$axios.onRequest(config => {
    config.progress = false;
});
```

**Comment by manniL** [comment]
@delanoflipse described the problem quite well, it *is* an axios issue however. A fix came with https://github.com/axios/axios/pull/2207 but a release is still pending.

**Comment by tomshaw** [comment]
```
.nuxt-progress {
  visibility: hidden;
  width: 0;
  height: 0;
  clip: rect(0,0,0,0);
  pointer-events: none;
  opacity: 0;
}
```

**Comment by karambafe** [comment]
@tomshaw 
This solution completely disables the progress bar and it is not suitable if you need to disable the progress bar only for part of the requests

**Comment by tomshaw** [comment]
@karambafe Disabling the progress bar using CSS is a legitimate solution. I spent an hour on [tomshaw.us](tomshaw.us) trying to figure out why this bizarre progress bar that came out of nowhere was showing up on each page request. The solution for me was to definitively hide it using CSS. IMHO it should be up to developers to purposely enable such functionality or developer their own solution.

**Comment by mrleblanc101** [comment]
It's already the case, did you even read the doc ?

**Comment by gaodeng** [comment]
workaround
```js

this.$axios.get('URL', { onDownloadProgress: () => {} });

```

**Comment by pi0** [comment]
Axios updated. Should be fixed with [v5.9.3](https://github.com/nuxt-community/axios-module/releases/tag/v5.9.3) .

**Comment by jb-alvarado** [comment]
The new version is fixing the issue what karambafe have explain. But is there a reason why the progress bar is still coming when axios is running in an `setInterval()` function?

Here a fork from karambafe:
https://codesandbox.io/s/codesandbox-nuxt-hu20j

**Comment by pi0** [comment]
@jb-alvarado I'll check it but think the best way is to create a new issue so we can track it easier.

**Comment by jb-alvarado** [comment]
@pi0, ok, I will create a new issue.

**Comment by sowinski** [comment]
Please link the issue to this thread. I have the same problem.
