### ISSUE TITLE
redirectError doesn't seem to be working

### ISSUE THREAD

**Issue by royscheeren** [nuxt-community/axios-module#27]
Hi,

I've got these settings in my nuxt.config.js:

``` 
axios: {
    credentials: false,
    debug: true,
    redirectError: {
      404: '/404'
    }
  }
```
However when visiting a page that doesn't exist, I do get the Nuxt page not found error but it doesn't redirect me to the `404` route.

**Comment by template01** [comment]
Hey. Any updates on this issue?

**Comment by bognix** [comment]
Same here :( when API returns 401 user is not redirected.

```
axios: {
  redirectError: {
    401: '/sign-in'
  }
}
```

**Comment by pi0** [comment]
We have a new workaround using `5.x` version. Please see #78.
