### ISSUE TITLE
Export CancelToken

### ISSUE THREAD

**Issue by padinko** [nuxt-community/axios-module#271]
### What problem does this feature solve?

Can `@nuxtjs/axios` export `CancelToken` too?
So I gan use only `import { CancelToken } from '@nuxtjs/axios';` which I already have in dependencies
instad of `import { CancelToken } from 'axios';` which need to be additionally added to dependencies

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c265">#c265</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. I'm sorry but it's not possible to directly import it from the module package. Axios will be automatically installed when you install axios module (@nuxt/axios) but if your IDE is complaining about this, you can always also directly add axios dependency as well. I'm closing this issue as it is more a feature request but #292 can also provide an easier shortcut when you don't need any import :)
