### ISSUE TITLE
baseURL should not use development defaults

### ISSUE THREAD

**Issue by matthieusieben** [nuxt-community/axios-module#273]
If eveything else fails, `baseURL` will default to `http://localhost:3000`.

While this is nice in dev environement, it might cause production environement to use `http://localhost:3000` as default, if not configured properly.

This lead to error in my deployment because I didn't configure the module correctly but din't realise my mistake until it was too late.

I believe that a better behaviour would be to throw ASAP in that case, preventing the deployment of faulty code.

**Comment by you06** [comment]
I'm facing the same issue. After looking into the source code, I found that the `addPlugin` function in axios middleware  generate template from the environmental variables while running `npm run build` or `yarn build`.

For example
```sh
yarn build
HOST=0.0.0.0 API_HOST=192.168.3.10 yarn start
```
The `baseURL` will be `http://localhost:3000`
```sh
HOST=0.0.0.0 API_HOST=192.168.3.10 yarn build
yarn start
```
Then the `baseURL` will be `http://192.168.3.10:3000`

It's strange.

IMO, the `baseURL` should follow the environmental variables when running `npm run start` or `yarn start`.

**Comment by you06** [comment]
And I find further discussions here https://github.com/nuxt/nuxt.js/issues/5100
The basic issue is that there are not any mechanisms for nuxt to inject env vars into browser runtime. You can find some work-arounds in the above issue.
