### ISSUE TITLE
Can I use axios-module in non-vue files?

### ISSUE THREAD

**Issue by 0pt1m1z3r** [nuxt-community/axios-module#28]
I want use it in es6 classes.

**Comment by clarkdo** [comment]
axios-module is for easy axios integration with Nuxt.js. It creates axios instance inside plugin and only delegates to `ctx` as `$axios` and `app` as `axios`. 

So If your js is binded to Nuxt context, you can use `ctx.$axios` or `app.axios`, if not you may need to create a axios instance manually just like [plugin.template.js](https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.template.js#L129-L182) does.

We can also discuss if it's necessary to change the module to export the `axios` instance for normal js use.

**Comment by 0pt1m1z3r** [comment]
My version.

~/plugins/axios-port.js
```js
import { setClient } from '~/services/apiClient'

export default ({ app, store }) => {
  setClient(app.$axios)
}
```

~/services/apiClient.js
```js
let client

export function setClient (newclient) {
  client = newclient
}

// Request helpers
const reqMethods = [
  'request', 'delete', 'get', 'head', 'options', // url, config
  'post', 'put', 'patch' // url, data, config
]

let service = {}

reqMethods.forEach((method) => {
  service[method] = function () {
    if (!client) throw new Error('apiClient not installed')
    return client[method].apply(null, arguments)
  }
})

export default service
```

Use:
```js
import apiClient from '~/services/apiClient'

export default {
  async current () {
    return apiClient.get('...')
  }
}
```

**Comment by nikkanetiya** [comment]
@clarkdo I think it required to be able to use a module to export the axios instance for common import/require use. The way @0pt1m1z3r shown here will work, but I wish to export be part of this package which will allow me to use axios instance set by auth-module which will have data pre-set headers like tokens. Currently, I am using ENT models which is not vue files so I am not able axios instance created by axios-module.

**Comment by pi0** [comment]
In a nutshell, we can not make global exports because of SSR. If there is NO WAY to access nuxt instance, you have to use `window.$nuxt.$axios` but this only works for Browser. Axios is available at: 

- plugins
- vuex store
- pages
- middleware
- other modules

I recommend using a plugin to access nuxt context and axios instance.

**Comment by lukasborawski** [comment]
@0pt1m1z3r f... yeah this is working perfectly

**Comment by xxRockOnxx** [comment]
At first I thought I needed axios-module to use axios with Nuxt but in my usage, I found out I don't need especially I am used to doing the service-pattern like in Java. My gist might help those who do it like me.

Here's I do it: https://gist.github.com/xxRockOnxx/4c52ca0a59a970d6f02d310cdf0ddfe3
