### ISSUE TITLE
$axios is undefined in async asyncData method in production (nuxt build && nuxt start)

### ISSUE THREAD

**Issue by acrolink** [nuxt-community/axios-module#282]
### Version

[v5.6.0](https://github.com/axios-module/releases/tag/v5.6.0)

### Reproduction link

[https://jsfiddle.net/v4nedh6L/](https://jsfiddle.net/v4nedh6L/)

### Steps to reproduce

The following code works perfect in development (nuxt script):
```
  async asyncData({ $axios, params }) {
    let response = await $axios.get(`/api/items`)
    return { entities: response.data.data }
  }
```
However, in production (nuxt build && nuxt start) I get this error:
```
 ERROR  Cannot read property 'get' of undefined                            18:31:39

  at asyncData (03b2f45fe1a8907386a4.js:1:0)
  at C (server.js:1:0)
  at Promise.all.h.map.n (server.js:1:0)
  at Array.map (<anonymous>)
  at e.default (server.js:1:0)
```

### What is expected ?

Axios should work as it does in development.

### What is actually happening?

Error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c274">#c274</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@acrolink You need to have a module installed and configured with nuxt.
Please see https://axios.nuxtjs.org/

**Comment by ricardogobbosouza** [comment]
@pi0 can closed?

**Comment by jigarf504** [comment]
I have installed Axios module and configured it too. But still it is not worked in production. Please help me to get out of it.
