### ISSUE TITLE
Global error handling precedes local '.catch()', causing possible infinite loop

### ISSUE THREAD

**Issue by kissge** [nuxt-community/axios-module#285]
### Version

[v5.6.0](https://github.com/axios-module/releases/tag/v5.6.0)

### Reproduction link

[https://codesandbox.io/embed/axios-global-error-handling-vct01?fontsize=14](https://codesandbox.io/embed/axios-global-error-handling-vct01?fontsize=14)

### Steps to reproduce

None

### What is expected ?

Local error handling precedes and no alert is shown

### What is actually happening?

Global error handling precedes and alert is shown

### Additional comments?

When both a global error handling (via nuxt's plugin) and a local error handling (via '.catch()') are set, I would expect the former one works as 'default' error handler i.e. works only when there's no other ones handling the error instance.
However, current axios-module is not working as that.

(note: Some time before, a kind-of-dirty "hack" was known to monkey patch this problem (e.g. https://www.qcode.in/api-error-handling-in-vue-with-axios/), but this currently doesn't work because axios' behavior changed a year ago.
https://github.com/axios/axios/commit/5bfd2ea9f63e59efaef3f1a659b55bbb9778fce2#diff-91dcec0516f33811ee5fa71297160b3bR39 )

I think this is a design bug.
This also leads to infinite loop and consequent browser crash when some API call is invoked in global error handler, because that call cannot utilize '.catch()' mechanism, which is obviously undesirable.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c284">#c284</a>)</em></sub></div>

**Comment by pi0** [comment]
Closing as there is nothing to do with axios-module. Globally suppressing errors is probably not a good idea also what you return in `onError` is considered as response object so instead of `true`, we may use something like `{ error, data: {} }`

**Comment by nivv** [comment]
How is this supposed to be handled? I want to reject the error globally if there is no catch method locally.

This is what my `axios.js` configuration looks like:

```javascript

export default function ({ $axios, error: nuxtError }) {
    $axios.onError(error => {
        if (error.response.status === 500) {
            nuxtError({
                errorMessage: error.response.data.message,
                statusCode: error.response.status,
                message: 'Oj, ett serverfel har inträffat!',
                showStatusCode: true,
                icon: '💣'
            })
        }
        if (error.response.status === 404) {
            nuxtError({
                errorMessage: error.response.data.message,
                statusCode: error.response.status,
                message: 'Sidan kunde inte hittas',
                showStatusCode: true,
                icon: '🧐'
            })
        }
        if (error.response.status === 503) {
            nuxtError({
                errorMessage: error.response.data.message,
                statusCode: error.response.status,
                message: 'Sidan är nere för underhåll, strax tillbaka',
                showStatusCode: false,
                icon: '🏗'
            })
        }

        if (error.response.status > 500) {
            nuxtError({
                errorMessage: error.response.data.message,
                statusCode: error.response.status,
                message: 'Ett fel har inträffat',
                showStatusCode: true,
                icon: '💥'
            })
        }

        return Promise.reject(error)
    })
}
```

And this is an excerpt from a method that posts at form:
```javascript
        async sendMessage () {
            this.hasError = false
            this.generalError = false
            this.validationError = false
            try {
                await this.$axios.post('/api/contact-message', this.contact)
                this.formSent = true
            } catch (error) {
                this.hasError = true
                if (error.response.status === 422) {
                    this.validationError = true
                    this.validationErrorData = error.response.data
                } else {
                    this.generalError = true
                    return
                }
            }
        }
```

The desired outcome of this should be to show an error next to the form being posted, in the case of a response code `500` the error page is displayed instead resulting in loss of information in the form.
