### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by nachogarcia** [nuxt-community/axios-module#286]
### What problem does this feature solve?

At the moment, we have a global Axios instance with nice default configurations.

I need to have multiple instances with that same base configuration, but some extensions (baseUrl and headers).

I have this plugin to separate my domain services and it would be great to have the this feature

```
import ContentService from '@/infrastructure/services/ContentService'
import ClientService from '@/infrastructure/services/ClientService'

export default (ctx, inject) => {
  const httpClient = ctx.$axios

  const services = {
    content: new ContentService(httpClient),
    client: new ClientService(httpClient),
  }

  inject('services', services)
}
```

I've tried creating new instances with the provided defaults, but that way I don't get this module helpers

```
import axios from 'axios'
import ContentService from '@/infrastructure/services/ContentService'
import ClientService from '@/infrastructure/services/ClientService'

export default (ctx, inject) => {

  const services = {
    content: new ContentService(axios.create({ ...ctx.$axios.defaults, baseURL: '/contentApi' })),
    client: new ClientService(axios.create({ ...ctx.$axios.defaults, baseURL: '/clientApi' })),
  }

  inject('services', services)
}
```

### What does the proposed changes look like?

Have a `$axios.duplicate()` maybe? Or a way to easily apply all the helpers and defaults to an instance

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c285">#c285</a>)</em></sub></div>

**Comment by mercs600** [comment]
Yes... We have to do the same thing, that's why we don't use nuxt/axios in our module.

**Comment by mercs600** [comment]
aww wait, we can do it! @nachogarcia please look at it and let me know if it meet your needs. For us it would be perfect.

PR: https://github.com/nuxt-community/axios-module/pull/306

**Comment by nachogarcia** [comment]
Looks good to me! 😃
