### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by cgygd** [nuxt-community/axios-module#29]
![5349c36e-0e0e-4732-aab8-d991d6905b10](https://user-images.githubusercontent.com/2216048/30531051-413244bc-9c7e-11e7-9747-f091a3e9e745.png)

![e8234adc-64d0-4ad2-8613-c055f2284586](https://user-images.githubusercontent.com/2216048/30531081-74b7fa34-9c7e-11e7-9b53-2740b545e108.png)

**Comment by vadimsg** [comment]
+1

**Comment by vadimsg** [comment]
Just had the same error when i copied my .env file contents to remote and lost one letter. Check if your .env file is correct.

**Comment by cgygd** [comment]
I have used the nuxt-community installation project. Where is the.Env file configured?

**Comment by cgygd** [comment]
thx,Okay.
![ad602794-d12e-446b-bea6-ce33126c558f](https://user-images.githubusercontent.com/2216048/30576311-8dbc2e68-9d39-11e7-932e-68db80f743d7.png)

![7fcf1306-4ad8-43d6-9dd9-11ecbd7ae7ff](https://user-images.githubusercontent.com/2216048/30576315-9c1e4dec-9d39-11e7-8a1c-27a81b208800.png)
