### ISSUE TITLE
Current route.fullPath is out of date when called inside of an interceptor

### ISSUE THREAD

**Issue by chrislentz** [nuxt-community/axios-module#295]
### Version

[v5.6.0](https://github.com/axios-module/releases/tag/v5.6.0)

### Steps to reproduce

Make an axios API call after a route change after the initial SSR app load. 

```
export default function ({ $axios, store, route, redirect }) {
  $axios.onError((error) => {
    if (error.response.status === 401) {
      store.commit('misc/setRedirect', route.fullPath);

      redirect('/sign-in');
    }
  });
}
```

### What is expected ?

If I load the page on '/', then navigate to '/one' and make an axios request, the onError interceptor will return '/' via `route.fullPath`.

### What is actually happening?

It should return '/one'.

### Additional comments?

I was able to find a workaround by using `app` instead of `route`, but I wanted to report the bug.

Workaround: `app.router.currentRoute.fullPath`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c291">#c291</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @chrislentz I could not reproduce
Could you provide a repository?

**Comment by schellenbergk** [comment]
I got the same issue in my axios plugin:
```
export default function({ $axios, app, route }) {
  $axios.onError(error => {
    if (error.response.status === 401) {
      console.log("Axios 401: ", app.router.currentRoute.path, route.path)
    }
  })
}
```
`route.path` seems to be set to the route when the plugin was initialized, `app.router.currentRoute.path` seems correct

**Comment by pi0** [comment]
This is not a bug. When destructing an object references are kept. @schellenbergk solution for `app.router.currentRoute.path` seems best :)
