### ISSUE TITLE
Use axios-module inside another module?

### ISSUE THREAD

**Issue by stursby** [nuxt-community/axios-module#3]
Is this possible?

I was inspecting the `moduleOptions` but that doesn't seem to contain any reference to axios

```js
// all of this code is inside /modules/static.js

module.exports = function static(moduleOptions) { ... 
// moduleOptions.axios ??
```

OR trying to find it inside of `this`

```js
this.axios // undefined

// tried this too...
module.exports = function static(moduleOptions, { app }) { ...

app.axios.$get // doesn't work

...
```

Also tried importing `@nuxtjs/axios` but that is just the general package... not _my_ instance

```js
const axios = require('@nuxtjs/axios')
```

Hopefully I'm just missing something small!

**Comment by pi0** [comment]
Hi. We have a limitation: axios module provides  $axios in the runtime using plugins while modules live in the nuxt build process. Is there any reason why you need it there?

**Comment by stursby** [comment]
I was going to abstract my config.generate.routes into another module as it will eventually get quite large. Not a huge deal I guess, I can just use regular axios. Or perhaps create my own custom axios instance in ~/plugins and use that across the board?

**Comment by mheppner** [comment]
Yeah, I'm in the same situation as @stursby, I already have all of my API requests separated in another module. My store is importing that module and doing transformations on the inputs/outputs after executing the API functions. If I used this package, I'd have to pass down the axios instance from the page -> store -> API module, for every action.

With the old (0.x) plugin system (not sure if 1.x is different), we still had a way of instantiating something that could be imported anywhere.

**Comment by homerjam** [comment]
+1

**Comment by rAugustos** [comment]
+1

**Comment by pi0** [comment]
Unfortunately it is not possible with new Vue SSR mechanism (Shared global references per request). Other plugins can use `$axios` using their arguments just like `aysncData`
