### ISSUE TITLE
Method "$delete" conflicts with an existing Vue instance method. Avoid defining component methods that start with _ or $.

### ISSUE THREAD

**Issue by riteable** [nuxt-community/axios-module#30]
Suddenly getting this warning a bunch of times after building. I don't know how $delete could be conflicting with other methods. I haven't added any $delete methods myself, and have not added any other modules or plugins that could be causing this issue. When I remove `@nuxtjs/axios`, which is my only module at the moment, the error disappears. And there's also no $delete method on the instance anymore.

**Comment by onlyurei** [comment]
@riteable you probably still use a version before this commit on the old repo: https://github.com/nuxt-community/modules/commit/1ab2bd6

Vue may have introduced this warning in one of recent releases, if you didn't lock/shrinkwrap, or if you re-locked/shrinkwrapped you may start to get this warning - I just started to this this warning too when I relocked the packages today, and I upgraded `@nuxtjs/axios` to `^4.3.0` and the warning went away. A little digging revealed above.

**Comment by riteable** [comment]
Yep, that's it. Thanks!
