### ISSUE TITLE
Cannot create new https.Agent() within axios.init()

### ISSUE THREAD

**Issue by unr** [nuxt-community/axios-module#31]
When using the `axios.init()` function within `nuxt.config.js`, creating a new https.Agent() is quite difficult.

Importing https to be used constantly returns https is undefined.

```js
const https = require('https');

axios: {
	init(axios, context) {
		axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false });
	},
},
```

`https` will be undefined, and fail.

Importing https within the `axios.init()` callback also fails.

**Comment by pi0** [comment]
Please see the newer approach using `5.x`. Using nuxt plugins, you can easily achive this:

`plugins/axios.js`

```js
import https from 'https'

export default({ axios }) {
  axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false })
}
```

https://github.com/nuxt-community/axios-module#extending-axios

**Comment by alanaasmaa** [comment]
I had same issue and i tried the solution here but it didn't work for me.

What worked for me was environment variable `NODE_TLS_REJECT_UNAUTHORIZED="0"`
Maybe something we should implement into nuxt.js dev mode?

_Also i think the variable should be `$axios` not `axios`._

**Comment by laurentdebricon** [comment]
> Please see the newer approach using `5.x`. Using nuxt plugins, you can easily achive this:
> 
> `plugins/axios.js`
> 
> ```js
> import https from 'https'
> 
> export default({ axios }) {
>   axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false })
> }
> ```
> 
> https://github.com/nuxt-community/axios-module#extending-axios

Thank you, it worked for me.
The solution is indeed with $axios.

**Comment by AntoninSlejska** [comment]
Little update:

> plugins/axios.js

```
import https from 'https'

export default function({ $axios }) {
  $axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false })
}
```

See: https://axios.nuxtjs.org/extend
