### ISSUE TITLE
setHeader not working

### ISSUE THREAD

**Issue by MLDMoritz** [nuxt-community/axios-module#311]
### Version

[v5.8.0](https://github.com/axios-module/releases/tag/v5.8.0)

### Reproduction link

[http://example.com](http://example.com)

### Steps to reproduce

```js
$axios.setHeader('Content-Type', 'application/ld+json', [
    'get',
    'post',
    'delete'
  ])
  $axios.setHeader('Content-Type', 'application/merge-patch+json', 'patch')
```

Results in a correct config but axios is not picking up the correct headers for the requested method, eg patch.

It uses config.headers['Content-Type'] instead of config.headers.patch['Content-Type']

### What is expected ?

Correct header sent on PATCH request

### What is actually happening?

PATCH request uses default header

### Additional comments?
This is the `config.headers` object logged in `$axios.onRequest`:
```
common: {Accept: "application/ld+json", Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYX…xhHiztfOFfJ9rIdvhiRz1oUhMm7sSoWrgNNlgOZwCpfJ8Xovw"}
delete: {Content-Type: "application/ld+json"}
get: {Content-Type: "application/ld+json"}
head: {}
post: {Content-Type: "application/ld+json"}
put: {Content-Type: "application/x-www-form-urlencoded"}
patch: {Content-Type: "application/merge-patch+json"}
Content-Type: "application/json;charset=utf-8"
```

Setting the header in the request itself works fine and sends correct header:

```js
this.$axios
      .$patch(`users/${user.id}`, user, {
        headers: {
          'Content-Type': 'application/merge-patch+json'
        }
      })
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c308">#c308</a>)</em></sub></div>

**Comment by mrleblanc101** [comment]
Same

**Comment by pi0** [comment]
Thanks for report @MLDMoritz @mrleblanc101. Should be fixed by 6c5605df0b77e9e4df32ad1eaecb2eac60eb1c1d

**Comment by jasminetracey** [comment]
This issue is still present

**Comment by madStitcher** [comment]
I'm still having this issue as well

**Comment by JackHamer09** [comment]
I have this issue too...
I use nuxt-auth module and it doesn't always send headers, but sometimes it does, just randomly...

**Comment by jasminetracey** [comment]
@JackHamer09 thanks for the suggestion will try it out

**Comment by JackHamer09** [comment]
@jasminetracey I already found a solution. https://stackoverflow.com/questions/62013596/nuxtserverinit-does-not-receive-auth-cookies/62013728#62013728

**Comment by santerref** [comment]
I have found a solution, but I don't know if it's the best approach.

In axios lib, the `transformRequest` function set the header Content-Type to `application/json;utf8` if the data sent is an object:

```javascript
if (utils.isObject(data)) {
  setContentTypeIfUnset(headers, 'application/json;charset=utf-8');
  return JSON.stringify(data);
}
```

However, the default headers are set after this function, so it cannot use the defaults one in the nuxt.config.js file:

```javascript
// Transform request data
config.data = transformData(
  config.data,
  config.headers,
  config.transformRequest
);

// Flatten headers
config.headers = utils.merge(
  config.headers.common || {},
  config.headers[config.method] || {},
  config.headers
);
```

To solve the issue, I have set my Content-Type header in the root of the headers property of the axios config in my nuxt.config.js file:

```javascript
/*
** Axios module configuration
** See https://axios.nuxtjs.org/options
*/
axios: {
  credentials: true,
  proxy: true,
  headers: {
    'Accept': 'application/vnd.api+json',
    'Content-Type': 'application/vnd.api+json',
    common: {
      'Accept': 'application/vnd.api+json',
      'Content-Type': 'application/vnd.api+json'
    }
  }
},
```
