### ISSUE TITLE
Browser axios isn't getting same headers as SSR axios.

### ISSUE THREAD

**Issue by unr** [nuxt-community/axios-module#32]
When using the axios module in nuxt.config.js like:

```js
modules.exports = {
	modules: [
		'@nuxtjs/axios',
	],

	// axios module settings
	axios: {
		// allows our SSR instance to use headers in axios request
		proxyHeaders: true,
		credentials: true,
		// baseURL: 'https://local.dev/',

		// SSR Sets up the initial axios instance...
		init(axios, context) {
			axios.defaults.baseURL = context.env.api;
		},
	},
}
```

I am requesting data from my server at local.dev, from my express server frontend at local.dev:3000

When SSR makes the request, my cookies & session work fine through CORS with local.dev

However, when the browser loads, axios is no longer using same cookies/session as the SSR instance, and making a request to my local.dev server results in a new cookie/session each time

---

What is missing, to make the SSR version of axios work in the same manner as the browser version of axios? They're currently sending different headers.

**Comment by unr** [comment]
I'm also noticing...

If I use `axios: { baseURL: 'https://local.dev/' }` in the default config, my CORS request fails.

If I use the `init(axios, context) { axios.defaults; }` version,  my CORS works fine.

**Comment by unr** [comment]
In the end, I think this had more to do with my CORS issues, than I did axios-module.

However, if I use the init() function, I get entirely different results each time.

**Comment by pi0** [comment]
We have a completely new approach for determining base URL with `5.x`. Please read new docs. If still having problems, reopen this issue with a reproduction code.
