### ISSUE TITLE
Typings are incorrect for default axios within context

### ISSUE THREAD

**Issue by moleCuleFFF** [nuxt-community/axios-module#322]
### Version

[v5.9.0](https://github.com/axios-module/releases/tag/v5.9.0)

### Reproduction link

[http://nofreakingway.com](http://nofreakingway.com)

### Steps to reproduce

const cms: Plugin = (context, inject) => {
    console.log((context.app.$axios as AxiosStatic).create());
};

$axios in this instance uses the interface NuxtAxiosInstance which does not include the create method.

### What is expected ?

$axios should be an extended instance of AxiosStatic not AxiosInstance

### What is actually happening?

$axios is an instance of AxiosInstance

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c317">#c317</a>)</em></sub></div>

**Comment by pi0** [comment]
Should be fixed with [v5.9.3](https://github.com/nuxt-community/axios-module/releases/tag/v5.9.3) .

**Comment by davidlandais** [comment]
Still not fixed in current 5.9.5 release.
