### ISSUE TITLE
responseInterceptor does not get called on error

### ISSUE THREAD

**Issue by uptownhr** [nuxt-community/axios-module#33]
One good place to put some global error handlers is on the responseInterceptor, but looks like it is not being called when the request errors. 

```
responseInterceptor: (response, { store, redirect }) => {
      console.log('response', response)
      if (response.status.code == 401) {
        store.dispatch('logout')
        redirect('/login')
      }
      return response
    }
```

using version: 4.3.0

**Comment by pschmidt88** [comment]
Yeah, I got the same problem here.

**Comment by ahDDD** [comment]
I'm already set disableDefaultErrorHandler to true, but still nothing happens..

**Comment by XBT1** [comment]
+1

**Comment by pi0** [comment]
With `5.x` version, we have deprecated `responseInterceptor`. Instead there is a better solution to use nuxt plugins. 

Please see [Extending Axios](https://github.com/nuxt-community/axios-module#extending-axios) section and don't forget to migration guide :)
