### ISSUE TITLE
Please upgrade to axios 0.19.2 to get rid of XSS bug

### ISSUE THREAD

**Issue by mikkokut** [nuxt-community/axios-module#330]
### What problem does this feature solve?

Get rid of Axios XSS bug introduced in 0.19.1

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c325">#c325</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@mikkokut Resolved on v5.9.4
