### ISSUE TITLE
How to set the Client-IP on Nuxt Server side when making a request?

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [nuxt-community/axios-module#331]
Is there like a setting where this will be automatically enabled? To be specific I want to put the Client IP on **X-Real-IP** and **X-Forwarded-For** request headers. It says in in your [options](https://axios.nuxtjs.org/options#proxyheaders) that just setting the **proxyHeaders** true will set the Client Request headers which I think should have included the `X-Forwarded-For` or `X-Client-Ip`

**Comment by remagpie** [comment]
For those who ended up here, you can use the following code.
It will add the client's IP as the `X-Forwarded-For` header only when the request is sent from the server side.

```javascript
export default function ({$axios, req}) {
  if (req !== undefined) {
    const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress;
    $axios.onRequest((config) => {
      config.headers.common['x-forwarded-for'] = ip;
    });
  }
}
```

Put it under the `plugins` directory.
