### ISSUE TITLE
Passing data from store's action and throw the result into dynamic routes

### ISSUE THREAD

**Issue by fidellr** [nuxt-community/axios-module#34]
I'm trying to do login stuff, i fetch the user data from wht users sign in/input to the login form using 
`axios.post('some_sign_url', userdata) ` inside store action and i can't figured out how to redirect the users into like profile page with the `/_username/profile`routes which is the `_username` is must be dynamic, i think the documentation is not too clear for facing this kind of problem. I hope there's one example or maybe i didn't found tht example one..

**Comment by clarkdo** [comment]
Yes, you can refer https://github.com/nuxt-community/axios-module#errorhandler

**Comment by pi0** [comment]
There is a better approach with `5.x`. Please see latest docs.
