### ISSUE TITLE
Can't resolve 'defu' in '/code/.nuxt'

### ISSUE THREAD

**Issue by sobolevn** [nuxt-community/axios-module#342]
### Version

[5.9.5](https://github.com/axios-module/releases/tag/5.9.5)

### Reproduction link

[https://travis-ci.com/github/wemake-services/wemake-vue-template/jobs/297973346#L1250](https://travis-ci.com/github/wemake-services/wemake-vue-template/jobs/297973346#L1250)

### Steps to reproduce

1. Install this template: https://github.com/wemake-services/wemake-vue-template
2. Install dependencies with `npm i`
3. Run `npm run build`

### What is expected ?

I expect everything to work.

### What is actually happening?

Nuxt is not building. Here's an output:

```
ERROR in ./.nuxt/axios.js
Module not found: Error: Can't resolve 'defu' in '/code/.nuxt'
 @ ./.nuxt/axios.js 6:0-24 75:31-35
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c345">#c345</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @sobolevn thanks for reporting the issue. I'm closing it as it was not reproducible with latest `wemake-vue-template` version

**Comment by hnviradiya** [comment]
This issue is occurring with pnpm.
