### ISSUE TITLE
Use globalName instead of window.$nuxt in the plugin

### ISSUE THREAD

**Issue by jjelev** [nuxt-community/axios-module#345]
### What problem does this feature solve?

Nuxt global is leaking in the final build of application. However many modules reference this directly instead of refering to global name from configuration.

Can we use the globalName option in the nuxt config instead of $nuxt directly ?
https://github.com/nuxt-community/axios-module/blob/dev/lib/plugin.js#L129
```js
const $loading = () => (window.$nuxt && window.$nuxt.$loading && window.$nuxt.$loading.set) ? window.$nuxt.$loading : noopLoading
```

### What does the proposed changes look like?

```js
const $loading = () => (window.<%= options.globalName %> && window.<%= options.globalName %>.$loading && window.<%= options.globalName %>.$loading.set) ? window.<%= options.globalName %>$loading : noopLoading
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c347">#c347</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks for report @jjelev
