### ISSUE TITLE
When i use @nuxtjs/proxy module, all of the header's keys have transform to lowercase letter!

### ISSUE THREAD

**Issue by wongyujing** [nuxt-community/axios-module#348]

**Comment by pi0** [comment]
Hi. According to [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) headers are case-incentive. 

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.


Also, this is behavior of Node.js which always normalizes keys to lowercase:

https://stackoverflow.com/questions/43665540/nodejs-not-retaining-upper-case-of-request-header
