### ISSUE TITLE
Npm Audit Failure - High Sev http-proxy

### ISSUE THREAD

**Issue by SomethingNew71** [nuxt-community/axios-module#363]
### Version

[v5.10.3](https://github.com/axios-module/releases/tag/v5.10.3)

### Reproduction link

[https://anyproject.com](https://anyproject.com)

### Steps to reproduce

1. npm i @nuxtjs/axios
2. npm audit failure

### What is expected ?

No audit failure

### What is actually happening?

npm audit is delivering an error indicating a Denial of Service Vulnerability. 

### Additional comments?

![Screen Shot 2020-05-15 at 8.44.17 AM.png](https://cmty.s3.eu-west-1.amazonaws.com/100171714/2ae467c0-96aa-11ea-b870-53697c3e5221.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c358">#c358</a>)</em></sub></div>

**Comment by Espina2** [comment]
+1

**Comment by zoellner** [comment]
https://www.npmjs.com/advisories/1486 has the details

**Comment by pi0** [comment]
Hi. thanks for reporting :green_heart: I'm going to update both proxy and axios modules however according to the [advisory#1486](https://www.npmjs.com/advisories/1486), it is not effective on the way we use middleware:

> This is only possible when the proxy server sets headers in the proxy request using the proxyReq.setHeader function.

**Comment by pi0** [comment]
Hi [v5.11.0](https://github.com/nuxt-community/axios-module/releases/tag/v5.11.0) released
