### ISSUE TITLE
Release 5.10.4

### ISSUE THREAD

**Issue by DudaevAR** [nuxt-community/axios-module#365]
### What problem does this feature solve?

Please make a new release 5.10.4 with the last commit 'feat(types): add typings to axios config in `nuxt.config` (#357)'.
I found issue in @nuxt/auth v5. And new types are needed for a beautiful fix.

PR with @nuxt/auth fix:
https://github.com/nuxt-community/auth-module/pull/685

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c359">#c359</a>)</em></sub></div>

**Comment by DudaevAR** [comment]
@pi0 ping

**Comment by pi0** [comment]
Hi [v5.11.0](https://github.com/nuxt-community/axios-module/releases/tag/v5.11.0) released. sorry for delay.
