### ISSUE TITLE
Cancelling promise in response interceptor

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [nuxt-community/axios-module#369]
Basically, my question is the exact one here https://github.com/axios/axios/issues/583. It can be done via throw new `axios.Cancel('Operation canceled by the user.');`.. But how can I do this in nuxt axios module?? I can not see it in the document and I tried `$axios.Cancel('Error')` but returned **$axios.Cancel is not a constructor**

**Comment by ricardogobbosouza** [comment]
Hi @Dean-Christian-Armada 
Sorry for delay response
See docs https://axios.nuxtjs.org/usage#cancel-token
