### ISSUE TITLE
NuxtServerError: Request failed with status code 404 when accessing a nonexistent route

### ISSUE THREAD

**Issue by Seeman13** [nuxt-community/axios-module#373]
Hello! I try request on non existent route, but I got this error instead of page 404:
![Снимок4](https://user-images.githubusercontent.com/20585416/83941617-7b8ebe80-a7f5-11ea-894e-4f2d7789e773.png)
My query in store:
`async setData ({ commit }, { params, filters }) {
    try {
      const { data } = await this.$axios.$get('api/all-data', {
        params,
        paramsSerializer: () => qs.stringify(Object.assign(params, filters), {
          arrayFormat: 'repeat',
          strictNullHandling: true,
          skipNulls: true
        })
      })
      commit('SET_DATA', data)
    } catch (error) {
      throw error
    }
}`
Var params have next show:
....
{
 city,
 category: route.params.category,
 part
} ....

If I change params on ...params  all ok, no error, but query send without params.
If I send query with simple params correct - all ok.
But if at least one parameter is set incorrectly, i.e. for example, given a city that does not exist, an error always occurs.

On native Vue with axios the same query work correct!

**Comment by Seeman13** [comment]
I noticed that code not work with use operators async await
![Снимок6](https://user-images.githubusercontent.com/20585416/83943693-d977d200-a806-11ea-8c12-9a76b4470f60.png)
But this code work!
![Снимок5](https://user-images.githubusercontent.com/20585416/83943701-e1d00d00-a806-11ea-9c00-aeefbe07c019.png)

**Comment by rchl** [comment]
You are re-throwing the error in your first example so that will propagate to Nuxt and trigger page error. Don't do `throw error` from your `catch (error)` handler.

**Comment by lydiaMag** [comment]
I got the same error when accessing a static existing route , I tried with promise and with async await and both result with the same error . 
I run json-server on port 3000 and nuxt project on port 3333, The json-server is working properly but axios call return always with 404 error.

**Comment by lydiaMag** [comment]
When I created EventService with basic url all is working well , I think nuxt axios needs basic url 
const apiClient = axios.create({
  baseURL: `http://localhost:3000`,
  withCredentials: false,
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json'
  }
})

**Comment by Seeman13** [comment]
Thanks everyone for answers! I have decided this task long time.
It is working variant.
I don't remember exactly what was wrong.
But the essence of error was in incorrect params variable. Data was with value undefined.
![Снимок7](https://user-images.githubusercontent.com/20585416/96185281-54ce5a80-0f42-11eb-84c8-e05ebda68f91.png)

**Comment by yc-cool** [comment]
How did you solve it? I encountered the same problem
