### ISSUE TITLE
manually change axios baseUrl after build

### ISSUE THREAD

**Issue by Jackie733** [nuxt-community/axios-module#375]
now I have a question, how can I manually change axios baseUrl after build. just if specified url changed, I can manually change baseUrl, rather than rebuild the project

**Comment by beardcoder** [comment]
You can always use a absolute URL.

**Comment by Jackie733** [comment]
@beardcoder Can I put URL into the static file,  so I can change URL according to actual condition before 'nuxt start'

**Comment by beardcoder** [comment]
You can change it like this https://axios.nuxtjs.org/helpers.html#interceptors

**Comment by SkyaTura** [comment]
As added in #387 now you can use [Runtime Config](https://axios.nuxtjs.org/options.html#runtime-config)
