### ISSUE TITLE
Plugin not using runtime variables from $config

### ISSUE THREAD

**Issue by SkyaTura** [nuxt-community/axios-module#386]
### Version

[v5.11.0](https://github.com/axios-module/releases/tag/v5.11.0)

### Reproduction link

[https://codesandbox.io/s/pensive-joliot-og9ey](https://codesandbox.io/s/pensive-joliot-og9ey)

### Steps to reproduce

- Install `@nuxtjs/axios`
- Define a baseURL through module options
- Define a baseURL through public runtime config
- Define a baseURL through private runtime config
- Check which one is used in browser

### What is expected ?

Try to get `baseURL` from `$nuxt.$config.axios`

### What is actually happening?

Using only static compiled variable at build-time in `<%= options.baseURL %>`

### Additional comments?

This would also solve #88

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c363">#c363</a>)</em></sub></div>

**Comment by gregjmcdonald** [comment]
@SkyaTura Thank you for updating the module to use the new runtimeConfig! Am I right in thinking there is currently no way to consume a runtimeConfig variable for the proxy target alone? 

My config consists of:
```
proxy: {
  '/api/': {
    target: process.env.API_URL,
    pathRewrite: { '^/api/': '' },
    changeOrigin: true,
    xfwd: true
  }
}
```

Thanks

**Comment by IGassmann** [comment]
@gregjmcdonald you'll find the answer to that [here](https://github.com/nuxt-community/proxy-module/issues/72).
