### ISSUE TITLE
Add option to keep the Host header

### ISSUE THREAD

**Issue by C4Grey** [nuxt-community/axios-module#39]
I've noticed that this module is targeted for external APIs, but I have nginx proxy and load balancer, allowing redirects to different API servers along with Nuxt web server using one domain. Simplified example:
```nginx
location / {
#Nuxt
proxy_set_header Host $host;
...
}

location /auth {
#Authentication server
proxy_set_header Host $host;
...
}

location /rest {
#REST API server
proxy_set_header Host $host;
...
}
```
So I don't have to specify a baseURL, instead I may use relative URLs on both client and server sides, just like this:
```js
const headers = req && req.headers ? {...req.headers} : {}
const {data} = await axios.get('/rest/orders/my', {headers: headers})
```
But it will not work with axios-module, since it removing the Host header, which is proxied by nginx.

**Comment by pi0** [comment]
Hey! Now you can use [proxyHeadersIgnore](https://github.com/nuxt-community/axios-module#proxyheadersignore) option to customize and allow `host` header. Let me know if anything was wrong with this new feature.

Another tip, This can be simplified using $ suffix:
```js
const orders = await axios.$get('/rest/orders/my', {headers: headers})
```
