### ISSUE TITLE
Configure custom paramsSerializer

### ISSUE THREAD

**Issue by seanwash** [nuxt-community/axios-module#4]
How might one go about configuring a custom `paramsSerializer` for Axios? I'm working on an app that uses nested query string params and I need to use the `qs` lib with a different `arrayFormat`, but I'm not sure how to modify the global instance of Axios when using this module. What I'd like to do is something like:

``` Javascript
  axios: {
    baseURL: process.env.API_URL,
    paramsSerializer: (params) => {
      return qs.stringify(params, { arrayFormat: 'brackets' })
    }
  }
```

**Comment by seanwash** [comment]
I was able to set this up by using `requestInterceptor` and modifying the passed config to include `paramsSerializer`. Feel free to close this unless you have any suggestions?

``` Javascript
  axios: {
    baseURL: process.env.API_URL,
    requestInterceptor: (config, { store }) => {
      var qs = require('qs')
      config.paramsSerializer = (params) => {
        return qs.stringify(params, { arrayFormat: 'brackets' })
      }
      return config
    }
  }
```

**Comment by pi0** [comment]
Hi @seanwash. Sorry for late answer. I think using interceptors for customization would be the best option.

**Comment by ibufu** [comment]
```
axios.defaults.paramsSerializer = params => {
  return qs.stringify(params, {arrayFormat: 'repeat'});
};
```

**Comment by Maden-maxi** [comment]
```js
// ~/plugins/axios.js 
import qs from 'qs';

export default function ({$axios, app, store}) {

  $axios.onRequest(config => {
    config.paramsSerializer = params => qs.stringify(params, { arrayFormat: 'brackets' });
    return config;
  });
}

```

**Comment by leohdr** [comment]
> ```
> axios.defaults.paramsSerializer = params => {
>   return qs.stringify(params, {arrayFormat: 'repeat'});
> };
> ```

not working

**Comment by sontd-0882** [comment]
You should use `{arrayFormat: 'brackets'}` instead of `{arrayFormat: 'repeat'}`
