### ISSUE TITLE
Not working inside Docker

### ISSUE THREAD

**Issue by Tabrizian** [nuxt-community/axios-module#41]
Assume the following ```Dockerfile```:

```
FROM node:alpine

ENV HOST=0.0.0.0
EXPOSE 3000
WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
RUN npm install

COPY . /usr/src/app
RUN npm run build

ENV NODE_ENV=production
CMD npm start
```

Because I run ```npm run build``` when the environment variables have not been applied. This would cause to use the ```nuxt.config.js``` default value so not working as expected in the runtime. Because runtime is when environment variables are actually applied.

Do you have any solution for this?

**Comment by pi0** [comment]
You will need to use proxy module to prevent hard coding env variables in client bundle on build

**Comment by Tabrizian** [comment]
Can you give me an example of it?

**Comment by pi0** [comment]
I'm on mobile but there should be some usage info in the end of docs. (PS: refer to fandogh projects 😋)

**Comment by Tabrizian** [comment]
I found it. Thanks brother. :see_no_evil:
