### ISSUE TITLE
Broken server side request with cookies in 5.12.2

### ISSUE THREAD

**Issue by 1ed** [nuxt-community/axios-module#411]
After upgrading from 5.12.1 to 5.12.2 a server side axios request seems like does not send the original request cookies. `proxyHeaders` is tuned on and it seems to work so I think it is a breaking change in axios itself. 5.12.1 used axios 0.19.2 but  5.12.2 uses axios 0.20.0  and it has a lot of changes https://github.com/axios/axios/compare/v0.19.2...v0.20.0

**Comment by fsnlarson** [comment]
Broken in nuxt/auth as well https://github.com/nuxt-community/auth-module/issues/809

**Comment by usb248** [comment]
+1

**Comment by snsxn** [comment]
+1

**Comment by SebastianMieszczanczyk** [comment]
Is it connected with #428 ? Will it fix the issue?

**Comment by JerryKusenberger** [comment]
Was anyone able to find a workaround? I tried downgrading to 5.12.1... no luck. I made sure axios 0.19.2 was the only version installed.

**Comment by bmulholland** [comment]
Also reported in https://github.com/nuxt-community/auth-module/issues/884 and https://github.com/nuxt-community/auth-module/issues/891

**Comment by pi0** [comment]
Hi. I made PR #452 for fix but still need a reproduction. Seems headers passing from client, are properly proxified to API inside asyncData. Would be nice if can help to make reproduction because otherwise cannot fix...

**Comment by msonowal** [comment]
@pi0 
I will test and let you know

**Comment by msonowal** [comment]
@pi0 
Hi I have made a repo to reproduce it correctly you can check it here
https://github.com/msonowal/nuxt-auth-411

**Comment by pi0** [comment]
Thanks @msonowal that would be helpful yet to fix but in axios-module, we need bare minimum reproduction without depending on auth module. Taking above this into account, must suspicious change in axios that broken auth, was https://github.com/axios/axios/pull/1845 which if in auth module, we try to set cookie headers to `null`, original proxified ones will be discarded.

**Comment by 1ed** [comment]
I have just added a minimal reproducer https://github.com/nuxt-community/axios-module/pull/452#pullrequestreview-550984666

**Comment by pi0** [comment]
Issue finally solved by [v5.12.4](https://github.com/nuxt-community/axios-module/releases/tag/v5.12.4). Special thanks again @1ed for making issue and helping for reproduction <3

**Comment by 1ed** [comment]
Thanks for your great work!

**Comment by JerryKusenberger** [comment]
Thank you so much @pi0. I've already tested and pushed this change into production. Can confirm it has fixed a lot of strange issues we were having.

**Comment by dajpes** [comment]
Same here, after updating to the latest version (5.12.5), auth module issues from SSR are now fixed
