### ISSUE TITLE
How to type $axios when extending it?

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/axios-module#415]
Doc: https://axios.nuxtjs.org/extend/

```js
import https from 'https'
// import { NuxtAxiosInstance } from '@nuxtjs/axios'

export default function ({ $axios }: any) {
  $axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false })
}

```

I've tried to use `NuxtAxiosInstance` but it won't work.

**Comment by pi0** [comment]
Hi @webcoderkz would you please create a reproduction repository to check?

**Comment by webcoderkz** [comment]
It's just an axios.ts file inside "@/plugins/axios.ts":

![image](https://user-images.githubusercontent.com/5739191/91967316-e25c3f00-ed34-11ea-969a-b172f371d982.png)

**Comment by pi0** [comment]
I see but in order to check, without having a repository i have to create one myself to ensure answer is correct and it takes lots of time per day if have to do for each issue. So as a blind answer, is i think we can use `Context` type:

```ts
import https from 'https'
import { Context } from '@nuxt/types'

export default function ({ $axios }: Context) {
  $axios.defaults.httpsAgent = new https.Agent({ rejectUnauthorized: false })
}
```

**Comment by webcoderkz** [comment]
Context works, thanks! Ok, i see now, sorry for inconvenience.

**Comment by Mini-ghost** [comment]
I have same problem when I use `context.$axios` in plugins, I import `Plugin` type from `@nuxt/types`, but that is not useful

![image](https://user-images.githubusercontent.com/39984251/97964406-b07a5e00-1df3-11eb-8490-82a391da6b0c.png)
