### ISSUE TITLE
Is axios a consumer of a backend or is it the backend for next?

### ISSUE THREAD

**Issue by rlam3** [nuxt-community/axios-module#43]
Is axios a consumer of a backend or is it the backend for next?
I'm confused... Thanks!

**Comment by pi0** [comment]
Hi. Actually axios "makes requests" to the backend.

**Comment by rlam3** [comment]
@pi0 Thanks! I was wondering if we are able to have access to control the baseUrl version if need be.

**Comment by clarkdo** [comment]
@nuxtjs/axios has automatically add libs into `vendor`.

external-packages showed how to use external packages, `vendor` is for adding libs into vendor bundle, `axios` is just for a example.

`axios-module` is for easier to construct a `axios` instance which includes some specific configs and interceptors, you can also use `vendor` together with module to add axios into vendor bundle:

```js
{
  modules: [
    '@nuxtjs/axios',
  ],

  axios: {
    // proxyHeaders: false
  },

  build: {
    vendor: ['vue-notifications']
  },
}
```

**Comment by rlam3** [comment]
@clarkdo @pi0 is there a more modular way of configuring nuxt applications? nuxt.config.js seems to be just one big file. any way to separate production/development/staging configurations? Thanks.

**Comment by clarkdo** [comment]
`nuxt` command supports `--config-file` or `-c` to specify the path to nuxt.config.js file.
you can define different config files in different npm scripts or use https://github.com/motdotla/dotenv.
