### ISSUE TITLE
Impossible to perform properly the delete requests (update to axios 0.21.0)

### ISSUE THREAD

**Issue by brccosta** [nuxt-community/axios-module#442]
Dear guys,

The Data option not being set in axios.delete in v0.20! See: https://github.com/axios/axios/issues/3268, https://github.com/axios/axios/issues/3220#issuecomment-688566578

Such a problem has been solved in axios 0.21.0. Is is possible to use such a version?

**Comment by ricardogobbosouza** [comment]
Hi @brccosta 
Resolved in [v5.12.5](https://github.com/nuxt-community/axios-module/releases/tag/v5.12.5)
