### ISSUE TITLE
headers are overwritten

### ISSUE THREAD

**Issue by jakubm95** [nuxt-community/axios-module#444]
Hello,
I've updated to the latest version and this 
`{ headers: { Accept: 'application/json' } },`
 removes the globally added headers

```
const result = await $axios.get(
        `${env.api}/products/${route.params.slug}`,
        { headers: { Accept: 'application/json' } },
        {
          params: {
            showOther: true,
          },
        },
      );
```

**Comment by pi0** [comment]
Hi @jakubm95 issue solved by [v5.12.4](https://github.com/nuxt-community/axios-module/releases/tag/v5.12.4)
