### ISSUE TITLE
Calling API request from store/component gives CORS error

### ISSUE THREAD

**Issue by Stalex89** [nuxt-community/axios-module#446]
I'm trying to send get request with query parameters to the API inside Nuxt component or Nuxt store, but it gives me an error of CORS.

I was trying multiple solutions:
1) Enable proxy on axios
2) Adding query parameters inside endpoint configuration instead of url
3) Adding `Access-Control-Allow-Methods: 'GET, POST, OPTIONS', Access-Control-Allow-Origin: '*'` to the header
4) Adding/removing trailing slash to the base url
5) Adding `credentials: false` to the axios header in `nuxt.config.js`

None of them works for me
I was checking the API endpoint in Postman, and it was working for me.
Also it works if you put the call code inside the asyncData method in page.

Can you tell me please what can be a cause of that? 

<img width="580" alt="Screenshot 2020-12-06 at 12 28 07" src="https://user-images.githubusercontent.com/23526237/101278889-ad8dd700-37be-11eb-864f-6056ada2d860.png">

This code in page works:

<img width="866" alt="Screenshot 2020-12-06 at 12 43 30" src="https://user-images.githubusercontent.com/23526237/101279172-b384b780-37c0-11eb-93a6-f564c1b01df8.png">
<img width="683" alt="Screenshot 2020-12-06 at 12 44 42" src="https://user-images.githubusercontent.com/23526237/101279225-1aa26c00-37c1-11eb-9ab9-c18d95fa8bf5.png">

However this code inside the component does not: 

<img width="1037" alt="Screenshot 2020-12-06 at 12 49 02" src="https://user-images.githubusercontent.com/23526237/101279291-85ec3e00-37c1-11eb-983d-212edd10a67e.png">
<img width="683" alt="Screenshot 2020-12-06 at 12 50 23" src="https://user-images.githubusercontent.com/23526237/101279325-d9f72280-37c1-11eb-8564-4acf90255958.png">

The same happens if I put the code inside the store:
<img width="808" alt="Screenshot 2020-12-06 at 12 56 27" src="https://user-images.githubusercontent.com/23526237/101279429-78838380-37c2-11eb-8d4c-24e11e91e9f7.png">

<img width="970" alt="Screenshot 2020-12-06 at 12 58 12" src="https://user-images.githubusercontent.com/23526237/101279463-bd0f1f00-37c2-11eb-820b-ac1cfd44ab7e.png">

<img width="685" alt="Screenshot 2020-12-06 at 12 58 48" src="https://user-images.githubusercontent.com/23526237/101279490-ef208100-37c2-11eb-8480-36cbf69d5632.png">

**Comment by pmcp** [comment]
Hi Stalex89, did you get it fixed, and can you share the fix?

**Comment by Stalex89** [comment]
@pmcp At first I made it wrong to put the headers into the client side. 

this should be put instead on the server side (in my case, I put it to the .htaccess file):

```
  <IfModule mod_rewrite.c>
      RewriteEngine On
      # Preflight OPTIONS requests handling
      RewriteCond %{REQUEST_METHOD} OPTIONS
      RewriteRule ^(.*)$ $1 [R=200,L]
  </IfModule>
  <ifModule mod_headers.c>
      Header always set Access-Control-Allow-Headers "X-Requested-With, Authorization, Content-Type, Request-Method"
      Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
      SetEnvIf Origin "^http(s)?://(.+\.)?(localhost)(:[0-9]+)?$" origin_is=$0
      Header always set Access-Control-Allow-Origin %{origin_is}e env=origin_is
  </ifModule>
```

int the 'SetEnvIf Origin' line you can set whatever domains you want to have access to the server api separated by '|' (like that: localhost|example.com|example.test.com )

As for the Nuxt part, you don't need to set up headers or proxies, just put this into nuxt.config.js (debug is not necessary): 
![Screenshot 2021-01-23 at 13 14 11](https://user-images.githubusercontent.com/23526237/105577947-159f7900-5d7d-11eb-8d73-e0f2acc725e0.png)

configuration may be different depending on which server you are using (Apache or Nginx)
