### ISSUE TITLE
Axios doesnt work on Chrome Mobile

### ISSUE THREAD

**Issue by texorexo** [nuxt-community/axios-module#447]
When creating any request on the axios module, it would return an `Network Error`.

This doesnt appear to be the case in other browsers since they just handle the case just fine. 

This is a problem occurs especialy for [my site](https://nuxt.vexaplex.repl.co). Which doesnt work when I test it.

**Comment by texorexo** [comment]
Yeah, It was a a CORS issue. Its fixed now.

**Comment by avral** [comment]
Same error on IOS (Safary) but, it works for the exactly same http url with regular axios.
