### ISSUE TITLE
cookie is sent only to my localhost http api, but not to my productive api running on https

### ISSUE THREAD

**Issue by tobkle** [nuxt-community/axios-module#45]
Calling my development microservices with http://localhost/api the credentials cookies are sent. Setting it to production to run against https://api.server/api it doesn't send the cookies any more. 

First I thought it was due to this, but by deactivating it in "plugin.template.js" it is still not working:
```javascript
  axios.interceptors.request.use(config => {
    // if (config.withCredentials === undefined) {
      // if (!/^https?:\/\//i.test(config.url) || config.url.indexOf(baseURL) === 0) {
        config.withCredentials = true
      // }
    // }
    return config
  });
```
Can anyone give me a hint how you are calling your microservices api?

**Comment by pi0** [comment]
Hi. While my answer would not be exactly your question, but i HIGHLY recommend using proxy module for your microservice deployments as it resolves problems with credentials and CORS.  A little guide on usage is at the end of docs. 

About your question: I think CORS header should be enabled to make XHR working ...

**Comment by tobkle** [comment]
Thanks for your fast valuable hint. It works with the following setup:

nuxt.config.js
```javascript
...
modules: [
  '@nuxtjs/auth',
  '@nuxtjs/axios',
  '@nuxtjs/proxy'
],

axios: {},

proxy: {
    '/api': 'https://api.server.org'
},
...
```

Starting nuxt:
  nuxt:axios BaseURL: http://localhost:3333/api (Browser: /api) +0ms
[HPM] Proxy created: /api  ->  https://api.server.org

'/api/auth/login' results now into 'https://api.server.org/api/auth/login'

Cookies are transferred as expected.
