### ISSUE TITLE
How access to context param in asyncData func ?

### ISSUE THREAD

**Issue by joZephhh** [nuxt-community/axios-module#46]
Hello,
I've try to implement directly axios by the community module, but I've a problem. 

To do my api request I need route params so I pass as parameters `context` to asyncData to know request parameters. But it's seems that I can't pass `{app}` to access to the module and `context`  for route params together.

Simple example : 
```js
async asyncData (context, {app}) {
    console.log(context);
    console.log(app);
    const MyData = await app.$axios.$get(`my-api-url.com/categories/${context.route.params.slugName}`)
    return {MyData}
  }
```
`context` log works, but `app` log returns undefined
Thanks a lot !

**Comment by joZephhh** [comment]
Found! 
`context`have a key `app` ! 👍

**Comment by sloot14** [comment]
You could use `context.params`
