### ISSUE TITLE
Axios doesn't send query params from backend

### ISSUE THREAD

**Issue by davidmeirlevy** [nuxt-community/axios-module#468]
I'm using nuxt-axios from the vuex store:

the action does something like this:

```js
function ({ commit }, key)  {
    return this.$axios.$get(`api/something/${encodeURIComponent(key)}/data?target=front`)
      .then(list => commit("SET SOMETHING", list))
  }
```

Before you say something about the query, my initial usage of axios.get was was:

```js
this.$axios.$get(`api/something/${encodeURIComponent(key)}/data`,
      { params: { target: 'front' } })
```

The query params are sent as expected on:
1. dev environment.
2. from hybrid client-render, when the browser is rendering a page and doing this request.

but - when using the production environment, the query params are removed from the actual query.
I can see this request in the server logs.
and it only removed if it done from the backend-rendering, but not from the client-side when moving between pages after hydrate.
it just fetches the URL without the mentioned query params. very weird.

**Comment by davidmeirlevy** [comment]
The issue is simple. You see the query param at the URL?
So on backend side in production- there's no query params at all in all of the requests.
But the same code from the frontend is doing great.

**Comment by antsteyer** [comment]
hi @davidmeirlevy , what was the solution ? We are facing the same problem

**Comment by davidmeirlevy** [comment]
@antsteyeragorize i don't remember, sorry.
I switched to use fastify-dx last year because I had some complex usage I needed to resolve besides that issue.
