### ISSUE TITLE
[BUG] Automatic adjustment to https for base url server-side

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-community/axios-module#469]
I see the intended behaviour here is that is we are using https, that our server-side requests are converted to use the same (as well as client, which is understandable).
https://github.com/nuxt-community/axios-module/blob/master/lib/module.js#L110

In a situation using `docker-compose` where there becomes an internal network, it could make sense to still define an insecure path for the base URL as an internal network request.

Is this functionality necessary?

TIA.

**Comment by ricardogobbosouza** [comment]
Hi @silverbackdan 
Just disable `https`

```js
// nuxt.cofig.js
export default {
  axios: {
    https: false
  }
}
```

**Comment by silverbackdan** [comment]
Thanks for this! It won't change https back to insecure requests for client-side will it?

**Comment by ricardogobbosouza** [comment]
It does not change `baseURL` or `browserBaseURL`
https://github.com/nuxt-community/axios-module/blob/main/lib/module.js#L118

**Comment by silverbackdan** [comment]
Thank you very much
