### ISSUE TITLE
Enhancement: support compatibility with Electron 

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/axios-module#47]
Right now when the `@nuxtjs/axios` module is installed, the electron starter repo silently fails. 

I haven't been able to find out exactly why but I was able to successfully port over the main parts of the module (e.g. injecting it into nuxt and vue instance, setting up `setHeader` helper) and have it work.  Hopefully I'll have more time to come back and look into this if I need more of the code, but I'll open this issue in case anyone encounters the problem and wants more official support.

**Comment by alexisohayon** [comment]
👍  +1

Did you get it working in the end @alidcastano ?
Very interested in fixing that issue too ;)

Thanks!

**Comment by alidcastano** [comment]
Didn't figure out what caused the error but I was able to incrementally port over most of the code to get it working with the basic functionalities (injecting axios into context and being able to set headers). I would have sent a PR but ended up using graphql instead

**Comment by pi0** [comment]
Would you please provide a reproduction example and opening this issue again?
