### ISSUE TITLE
Access store  in error handler

### ISSUE THREAD

**Issue by mrcatman** [nuxt-community/axios-module#49]
I'm using JWT and refresh token authentication in my app (API and frontend are on different domains): 

errorHandler (error) {
var err = error.response;
var request = err.config;
if (err.status===401 && !request.__isRetryRequest ) {
				request.__isRetryRequest=true;
				return this.$axios.post('/users/refresh').then(res => {
					this.$axios.defaults.headers.common['Authorization'] = res.data.token;
					request.headers['Authorization'] = res.data.token;
					if (!res.data.success) {
						this.$axios.defaults.headers.common['X-Refresh-Token'] = '';
						request.headers['X-Refresh-Token'] = '';
					} 
					return this.$axios(request);
				}).catch((e)=>{
					this.$axios.defaults.headers.common['Authorization'] =  '';
					request.headers['Authorization'] = '';
				})
			  } else {
			}
		}
But I need to pass the new token into the store, and (if possible) set it server-side. How to do it?

**Comment by clarkdo** [comment]
Have you tried second param `vm` on `errorHandler `, there may have what you need inside `vm` object.

**Comment by kampfkuchen** [comment]
Did you try something like this: `errorHandler(error { store }) { store.state.token = res.data.token }`?

**Comment by pi0** [comment]
Axios `5.x` has a better solution for handling errors. Please see the docs.
