### ISSUE TITLE
Unable to catch JSON ERROR response inside both plugin/axios.js and vue component $axios catch() - was working some days back

### ISSUE THREAD

**Issue by ajingopi-bridge** [nuxt-community/axios-module#490]
### Issue with latest versions of `@nuxt/axios`

Tested versions

```
"@nuxtjs/axios": "^5.13.1",
"core-js": "^3.9.1",
"nuxt": "^2.15.3"
```

`plugins/axios.js`

```
export default function ({ $axios, app, error: nuxtError }) {
    $axios.onError((error) => {
        console.log(error)
        return Promise.reject(error)
    })
}
```

`vue component`
```
this.$axios
  .$put('/api/update', {test: 'test'})
  .then((response) => {
    console.log(response)
  })
  .catch((error) => {
    console.log(error)
  })
```

**What is expected?**
Output JSON response inside both `plugin/axios.js` and component `$axios` `catch()`

**What happened?**

> Error: Request failed with status code 400
>     at createError (createError.js?2d83:16)
>     at settle (settle.js?467f:17)
>     at XMLHttpRequest.handleLoad (xhr.js?b50d:62)

![image](https://user-images.githubusercontent.com/46883176/115401220-ccd64f80-a207-11eb-8bfa-c036812d0e59.png)

**This was working pretty well till I updated @nuxt/axios 1 week back.**

But I am not sure it's due to the versions.
I have tried downgrading versions, but nothing really worked.

I tried with extremely new nuxt app with just @nuxt/axios only in it. Same issue.

Added a sandbox here to reproduce.

https://codesandbox.io/s/upbeat-hodgkin-8sx32

**Comment by pi0** [comment]
You need to use `error.response?.data` in order to access json error in response. See updated sandbox: https://codesandbox.io/s/spring-wood-upvcv?file=/plugins/axios.js

**Comment by ajingopi-bridge** [comment]
That fixed it. Great thanks.

But it was accessing successfully like this before
![image](https://user-images.githubusercontent.com/46883176/115536674-aff95500-a2b7-11eb-8fb3-8c9441062203.png)
and I could catch it in like this in callbacks
![image](https://user-images.githubusercontent.com/46883176/115536910-e3d47a80-a2b7-11eb-8bfa-5be3a27935f3.png)

I need to update all the existing places now..!!
