### ISSUE TITLE
Unable to access response.headers

### ISSUE THREAD

**Issue by bin4ryio** [nuxt-community/axios-module#5]
Hi there, I am running a backend server that correctly expose a few headers such as `access-token`. However I'm unable to access these headers using `console.log(response.headers)` which result `undefined`.

Chrome dev tools correctly display the requests:
![2017-08-19_21 01 28_valkyrie_ss](https://user-images.githubusercontent.com/21124691/29486827-bd87bd5e-8521-11e7-9c42-ac8d42074477.jpg)

Here is how my store action looks:
```
  async signIn ({ commit, dispatch }, { axios, email, password }) {
    try {
      const response = await axios.$post('auth/sign_in', {
        email: email,
        password: password
      })
      console.log(response)
      console.log(response.headers) // Undefined
      dispatch('clearAuthError')
    } catch (error) {
      console.log(error)
      dispatch('setAuthError', error.response.data.errors)
    }
  },
```

If I enable `debug: true` in axios module then it will show as expected in console:
![2017-08-19_21 03 49_valkyrie_ss](https://user-images.githubusercontent.com/21124691/29486838-f4697f4c-8521-11e7-839f-b6b91e15bfa2.jpg)

Is this an upstream problem? Please advice, cheers.

**Comment by pi0** [comment]
Hi. No that's simply because you are using the fetch style methods and it just returns body! For access headers use `await axios.post` (Without $)

**Comment by bin4ryio** [comment]
Did not realize the differences, thank you so much @pi0.
