### ISSUE TITLE
 No 'Access-Control-Allow-Origin'  --- NUXT

### ISSUE THREAD

**Issue by j17hernandez** [nuxt-community/axios-module#500]
Hola, estoy intentando conectar backend django con frontend Nuxt, cuando intento hacer uan petición me aparece este problema en la consola: 

Access to XMLHttpRequest at 'http://localhost:8000/api/1.0/usuarios' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Mi configuración es esta

modules: [
    ['@nuxtjs/axios'],
]

  axios: {
    baseURL: 'http://localhost:8000/api',
    proxyHeaders: false,
    credentials: false,
},

**Comment by FearHeim** [comment]
Lograste resolver el problema?

**Comment by j17hernandez** [comment]
Hola @FearHeim , si era algo en backend, estoy usando Django

Al momento de hacer el endpoint me mostraba ese error en consola, luego de haber instalado corsheaders y haberlo configurado dejó de salir el error
