### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by rodrigopv** [nuxt-community/axios-module#501]
Transpile of defu back to CommonJS breaks webpack as it doesn't support mixing different types of imports.

Had to solve it using:
```
-    "@nuxtjs/axios": "^5.12.5",
+    "@nuxtjs/axios": "5.13.1",
```

Not sure if I did roll back to the exact version that fixes the issue, but that was the last working one for the nuxt project I'm working on.

![image](https://user-images.githubusercontent.com/198869/119064291-0b972b00-b9a9-11eb-9384-766c3b814d9e.png)

Might be related to #498 
Please check also https://github.com/unjs/defu/issues/28

**Comment by pi0** [comment]
Can you please help to create a reproduction by forking [this sandbox](https://codesandbox.io/s/adoring-gareth-3mofx?file=/pages/index.vue)? That would be much help in finding the issue. Knowing exact versions of nuxt, node and axios that causes this can also be helpful.

**Comment by rodrigopv** [comment]
Hi,

Unfortunately I've been unable to isolate the environment in the sandbox you sent to reproduce the bug. I've been trying a couple hours from now, importing almost all packages.

The nuxt site I'm working on it's a pretty complex project. From package-lock.json:
```
    "nuxt": {
      "version": "2.15.6",
```
```
    "@nuxtjs/axios": {
      "version": "5.13.4",
```
```
     "defu": {
      "version": "5.0.0",`
```

The project itself has 54 dependencies and I'll keep trying to make the minimum set of packages needed to trigger this bug. From what I've read, in order to trigger the error, webpack should try to make a bundle that includes different types of imports (from dependencies that use export default, module.exports and require).

**Comment by pi0** [comment]
I see it might be sometimes hard to reproduce. You might want to try changing nuxt to `nuxt-edge` (potential fix https://github.com/nuxt/nuxt.js/pull/9180) and it might be also because of different resolution strategy of npm vs yarn (sandbox and tests are based on yarn).

In either way if even nuxt-edge didn't fix the issue, would be happy having a quick call to check issue on your website. (https://calendly.com/pi0)

**Comment by rodrigopv** [comment]
I finally managed to reproduce the issue 🔥

https://codesandbox.io/s/polished-haze-l8j4k

on nuxt.config.js:
```
    babel: {
      presets: ["@babel/preset-env"],
      plugins: [
        "@babel/plugin-proposal-class-properties",
        ["@babel/plugin-transform-runtime", { regenerator: true }]
      ]
    }
```

and the following packages:
```
  "dependencies": {
    "@nuxtjs/axios": "^5.12.5",
    "babel-runtime": "^6.26.0",
    "nuxt": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.13.1",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-transform-runtime": "^7.13.4",
    "@babel/preset-env": "^7.12.17"
  }
```

I'm not really sure if this the right way to use babel, as there is also a @nuxt/babel-preset-app package (I started working on an existing codebase with this).

**Comment by rodrigopv** [comment]
Forgot to comment that nuxt-edge doesn't solves this case and also both yarn and npm get into the same result

**Comment by pi0** [comment]
Hi @rodrigopv. I added a fix that solves both sandbox error and keeping ie11 compat. Can you please try  v5.13.5?

**Comment by datikken** [comment]
I think we still have a problem here

**Comment by pi0** [comment]
Hi @datikken Can you please try recreating the lockfile and latest `5.13.5` version? [sandbox](https://codesandbox.io/s/interesting-chatelet-ewxew?file=/package.json) with latest dumps seems working.

**Comment by datikken** [comment]
Thank you for fast reply, seems like I've messed with enviroment

**Comment by rodrigopv** [comment]
Sorry for the delay in testing the new version. It seems that new release `5.13.5` makes nuxt render the page properly, but now when visiting the page after `npm run dev`, the following error appears on chrome console:

![image](https://user-images.githubusercontent.com/198869/120385406-5f810880-c2f5-11eb-9503-cb7011684bae.png)

Please note that:
- I ran `npm update` and indeed I'm running version `5.13.5`
- from package-lock.json:

```
    "@nuxtjs/axios": {
      "version": "5.13.5",
      "resolved": "https://registry.npmjs.org/@nuxtjs/axios/-/axios-5.13.5.tgz",
      "integrity": "sha512-GyeuiseDCwfRGDQH/gK+lngCseZS3SQm3q6xqiVx5xQnzCqokojN3uJkNB0DdHCowBP1aim+mDhu3spzcCnyBg==",
      "requires": {
        "@nuxtjs/proxy": "^2.1.0",
        "axios": "^0.21.1",
        "axios-retry": "^3.1.9",
        "consola": "^2.15.3",
        "defu": "^5.0.0"
      },
```
- Tried deleting both `node_modules` and `.nuxt` to avoid some inconsistency issue
- At nuxt dev output it just shows this now:
```
"export 'default' (imported as 'defu') was not found in 'defu'                                friendly-errors 16:23:18
```

Also seen on Chrome console:
```
[HMR] bundle 'client' has 1 warnings
client.js?1b93:196 ./.nuxt/axios.js 73:31-35"export 'default' (imported as 'defu') was not found in 'defu'
```

This is happening on the same project that uses babel transpile for some reason (I think we should get rid of IE11 anyway)

**Comment by andorfermichael** [comment]
I have the same issue.

It happened to me after doing  `yarn add --dev jest @nuxt/test-utils`

And also when installing nuxt-i18n v6.27.1 or v6.27.2 (see https://github.com/nuxt-community/i18n-module/issues/1217)

**Comment by andorfermichael** [comment]
adding defu to package json solved the issue for me
