### ISSUE TITLE
Bug: NuxtAxiosInstance no longer exported

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-community/axios-module#555]
## Issue
The interface is no longer exported from type definitions and also results in an issue with the `vuex.d.ts` file:
`https://github.com/nuxt-community/axios-module/blob/main/types/vuex.d.ts` as this will try to import it as well.

## Solution:
NuxtAxiosInstance should be exported here:
`https://github.com/nuxt-community/axios-module/blob/main/types/index.d.ts`

## Related and possibly related:
- https://github.com/nuxt-community/axios-module/issues/550 (could be mis-diagnosis because it does extend AxiosStatic, so perhaps the type isn't imported for this user)
- https://github.com/nuxt-community/axios-module/issues/547 (same issue)
- https://github.com/nuxt-community/axios-module/issues/545 possible mis-diagnosis again as it should extend Axios interfaces which includes `get`

**Comment by dubst3pp4** [comment]
Also affects our projects with `nuxt` 2.15.8 and `@nuxtjs/axios` 5.13.6.

**Comment by ThomasBerne** [comment]
I have the same problem

**Comment by toshi-ue** [comment]
I have the same problem.
I get the following error by vscode.

```
Module '"@nuxtjs/axios"' has no exported member '$axios'.
```
or 
```
NuxtAxiosInstance not found in '@nuxtjs/axios'
```

Could anyone Help me?

**Comment by silverbackdan** [comment]
Ping @pi0 (sorry I know you've been very helpful on issues in the past, thought I'd bring this to your attention in case it's a quick fix or you may ping someone who is best placed to take a look?)

**Comment by amirhoseinsalimi** [comment]
The solution is to use `import type` like so:

`import type { NuxtAxiosInstance } from '@nuxtjs/axios';`

**Comment by silverbackdan** [comment]
Hi @amirhoseinsalimi

The `NuxtAxiosInstance` is not being exported to be able to import as a type.

Now it is here:
https://github.com/nuxt-community/axios-module/blob/main/types/index.d.ts

It should be `export interface NuxtAxiosInstance ...` to work no?

**Comment by silverbackdan** [comment]
@amirhoseinsalimi How cool. Thanks for your time investigating and the solution. It's certainly resolved the issue for me so will close the issue and the detail you've given will stick with me for any type imports in future too. You rock.

**Comment by amirhoseinsalimi** [comment]
Thank YOU for asking this so I could think more about types :D. I'll update this thread once I get more information about this behavior.
