### ISSUE TITLE
errorHandler ctx.redirect does not work on client side

### ISSUE THREAD

**Issue by cdesquilbet** [nuxt-community/axios-module#58]
Hello,

We want to redirect to '/maintenance' page when response's status is 503.

To implement this feature, we override ```errorHandler``` in nuxt axios config, as explained in https://github.com/nuxt-community/axios-module#errorhandler.

Using ```ctx.redirect```, the redirection works fine on first hit (server mode).
However, the redirection does not work with nuxt-links (client mode).

For now, we use ```window.location``` like this :
```
errorHandler (error, ctx) {
    if (error.response.status === 503) {
        if (ctx.isServer) {
            ctx.redirect('/maintenance');
        } else {
            window.location = '/maintenance';
        }
    }
    return Promise.reject(error);
},
```

This solution is not really satisfying.
Is there a better implementation, or are you planning to fix ```ctx.redirect``` on client side ?

Thank you in advance,

Clotilde

PS: We also tried with ```redirectError```as said in https://github.com/nuxt-community/axios-module#redirecterror
We are facing the same problem, probably because standard ```errorHandler``` also uses ```ctx.redirect```

**Comment by wuyongzhi** [comment]
i found the same problem

**Comment by wuyongzhi** [comment]
i think this method can be used to solve temporarily: 

```
errorHandler(err, ctx) {
  ctx.app.router.push('/path-to-redirect')
}
```

**Comment by jrs320** [comment]
waiting the solution online

**Comment by canhkieu** [comment]
Waiting...

**Comment by canhkieu** [comment]
We can not get code by: error.response.status
It's return undefined

**Comment by pi0** [comment]
Hi. With `5.x` version, you can use a Nuxt plugin to handle errors and do redirects. Please see [Extending Axios](https://github.com/nuxt-community/axios-module#extending-axios) section and also read [Migration Guide](https://github.com/nuxt-community/axios-module/wiki/Migration-guide) before upgrading.

**Comment by damienbeaufils** [comment]
@pi0 Thanks for this new version! It will be clearer now.
I migrate my old `errorHandler` code to the new plugin system explained in Extending Axios section, but I had an issue with the example: I had to replace `error.code` with `error.response.code`.
So 

```
export default function ({ $axios, redirect }) {
  $axios.onError(error => {
    if(error.code === 500) {
      redirect('/sorry')
    }
  })
}
```
became
```
export default function ({ $axios, redirect }) {
  $axios.onError(error => {
    if(error.response.status === 500) {
      redirect('/sorry')
    }
  })
}
```

Is it expected or is it an issue?
