### ISSUE TITLE
Export `NuxtAxiosInstance` typings

### ISSUE THREAD

**Issue by apgapg** [nuxt-community/axios-module#587]
Currently If I need a custom axios instance, I need to provide typings like this:

```ts
declare module 'vue/types/vue' {
  interface Vue {
    $axiosLogin: NuxtAxiosInstance
  }
}
```

Here to provide type of `$axiosLogin` I need to use `NuxtAxiosInstance`. But in typings we see the interface is not exported.

https://github.com/nuxt-community/axios-module/blob/d8c99e5edbd2d8ac7d3abe186dd435922e7e1a31/types/index.d.ts#L6

I cant do `import { NuxtAxiosInstance } from '@nuxtjs/axios'`

**Comment by itsahmedjasim** [comment]
@apgapg Import it like `import type { NuxtAxiosInstance } from '@nuxtjs/axios'`

**Comment by itsahmedjasim** [comment]
duplicated #547

**Comment by apgapg** [comment]
Thanks.
