### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by karudo** [nuxt-community/axios-module#6]
```javascript
// In store
{
  actions: {
    async getIP ({ commit }, { axios }) {
      const ip = await axios.$get('http://icanhazip.com')
      commit('SET_IP', ip)
    }
  }
}
```
It seems to me there is error in documentation, because second argument of action is payload, payload does not contain `axios`

**Comment by mheppner** [comment]
I don't believe that is an error, you need to pass the axios instance down from the component/page yourself. Look at the snippet above where you found this example in the docs...it shows passing down `this.$axios` when calling the store action.

**Comment by karudo** [comment]
Ah, I see, my fault. But passing `axios` via payload is very strange way
