### ISSUE TITLE
404? What might be wrong here?

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt-community/axios-module#60]
Hi,

Trying out the module. I have put my json in an /api folder in the project root.
code looks like this and the request url seems correct.

Error:
GET http://localhost:3000/api/studio/index.json 404 (Not Found)

Code:
```
  async asyncData ({ app }) {
    let { data } = await app.$axios.$get('/studio/index.json')
    return { content: data }
  },
```

Any idea what might be wrong?

**Comment by BruceHem** [comment]
@jesperlandberg putting your .json file in the api folder doesn't mean the endpoint exists. Until u make it.

**Comment by pi0** [comment]
@BruceHem is correct. If what you need is just serving static json content, you can create `static/api/studio/index.json` file and it will work :)

**Comment by jesperlandberg** [comment]
@BruceHem okey cool. Will try that!

**Comment by jesperlandberg** [comment]
@BruceHem worked better! Now the data is fetched both on route changee and page refresh. However, when i run nuxt generate (npm run generate) I get the following error, any idea what is the reason for this?

```
==== Error report ====
Route: '/studio'
Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
```

**Comment by BruceHem** [comment]
Honestly, I don't know what that could be. I never used generate at all.

**Comment by jesperlandberg** [comment]
@BruceHem might it be something about it trying to fetch data from my localhost? That isn't running because I'm "exiting" dev mode when running generate?

**Comment by pi0** [comment]
Unfrtounaly `nuxt generate` doesn't supports `serverMiddleware`. Upgrading to `5.0.0` may help to resolve issues. If still having problems, please reopen.

**Comment by levy9527** [comment]
well, it seems that you should `npm run dev` and keep that running,  then `npm run generate`.
my version "@nuxtjs/axios": "^5.0.1"

**Comment by westdrug** [comment]
@levy9527 @jesperlandberg   Hello, I also encountered the problem mentioned above. npm run generate time report the following error, may I ask what can be solved, thank you

> Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by 0721Betty** [comment]
> well, it seems that you should `npm run dev` and keep that running, then `npm run generate`.
> my version `@nuxtjs/axios`: `5.0.1`

emmm, I am facing the same issue! Has anyone solved it?
