### ISSUE TITLE
Multiple Proxy baseUrls instead of one with AXIOS calls.

### ISSUE THREAD

**Issue by fuzzybaird** [nuxt-community/axios-module#62]
I am trying to proxy several different API's (through http-proxy-middleware) from my Nuxt app. I like this module because it cleans up the context between the SSR and Client calls. But what I don't understand is how to set which proxy to use per AXIOS request.

nuxt.config.js
```javascript
  proxy: [
    ['/placeapi', { target: process.env.PROXY_PLACE_API_URL || 'https://maps.googleapis.com/maps/api/place/details/json', pathRewrite: { '^/placeapi': '' } }],
    ['/api', { target: process.env.PROXY_API_URL || 'http://myapi.io', pathRewrite: { '^/api': '/v2' } }]
  ],
```
I know i could set the baseUrl inside the `axios` config, but that just forces the url to one of the proxies I want. 

For example in my VUEX store, I want to set state with a couple of REST endpoints **and** avoid CORS issues.

```javascript
export const actions = {
  async addPlace ({ state, commit, rootState }) {
    // using /placeapi path proxy.
    let { data } = await this.$axios.$get(`/placeapi?placeid=ChIJ3yhwXkVgUocRuHn-Xhidp8A&key=__KEY__`)
    commit('addPlace', data.result)
  },
  async addMeta ({ state, commit, rootState }) {
    // using /api path proxy.
    let { data } = await this.$axios.$get(`/meta`)
    commit('addMets', data.result)
  }
}
```

**Comment by clarkdo** [comment]
You can use `http-proxy-middleware`, pls check https://github.com/nuxt-community/modules/tree/master/packages/proxy

**Comment by fuzzybaird** [comment]
@clarkdo I am sorry if I was not specific or clear enough; I am using http-proxy-middleware. It partners with the Axios-Module and sets a default of `yourdomain.com/api` as the proxy. I want to use multiple proxies. An example could look like this `this.$axios.$get('/json?more=params').proxy('/placesapi')`

**Comment by CKGrafico** [comment]
I can understand you.. seems that there is a problem with this module and proxy, not sure why but you have to remove the 'api' part of axios config 
```
['@nuxtjs/axios', {
            browserBaseURL: '/',
            baseURL: 'http://localhost:3000'
        }],
```

I don't like to have this baseURL like that but I'm still investigating.

Sincerely this plugins needs a refactor

**Comment by pi0** [comment]
@fuzzybaird The best option as @clarkdo suggested would be using Proxy. Please see docs for new 
 [Build-In proxy](https://github.com/nuxt-community/axios-module#proxy).

**Comment by wienska** [comment]
Hello! I've got similar problem -I would like to have two proxy urls but I can't understand how to switch between them. 

I have the following config and I would like to make requests to api2 sometimes. How can I pass prefix?
```
  axios: {
    proxy: true,
    prefix: '/api'
  },
  proxy: {
    '/api/': { target: process.env.API_URL, pathRewrite: { '^/api/': '' } },
    '/api2/': { target: process.env.FORM_URL, pathRewrite: { '^/api/': '' } }
  }
```

**Comment by thunderwin** [comment]
I need know as well

**Comment by luischinchillagarcia** [comment]
I was having the exact same problem and found a few places where they mentioned this working. I understand that you need prefix in order to get a non-dev env to work, however, `changeOrigin` handled that for me. The following worked for me:

```javascript
  axios: {
    proxy: true,
    // prefix: '/api' // avoid this
  },
  proxy: {
    '/api/': { target: process.env.API_URL, pathRewrite: { '^/api/': '' } , changeOrigin: true},
    '/api2/': { target: process.env.FORM_URL, pathRewrite: { '^/api/': '' } , changeOrigin: true}
  }
```

**Comment by kimcrab** [comment]
> Hello! I've got similar problem -I would like to have two proxy urls but I can't understand how to switch between them.
> 
> I have the following config and I would like to make requests to api2 sometimes. How can I pass prefix?
> 
> ```
>   axios: {
>     proxy: true,
>     prefix: '/api'
>   },
>   proxy: {
>     '/api/': { target: process.env.API_URL, pathRewrite: { '^/api/': '' } },
>     '/api2/': { target: process.env.FORM_URL, pathRewrite: { '^/api/': '' } }
>   }
> ```

No solutions yet?

**Comment by hieuho97** [comment]
Proxy does not work in static projects (nuxt generate). Static projects does not ship server middle-wares to production, therefore server middleware of proxy module will not work on any static project.
