### ISSUE TITLE
How to add token to each request header？

### ISSUE THREAD

**Issue by NeilSong** [nuxt-community/axios-module#63]
When a user enters my website, i create a token that belongs to this user. When sending the first request, i send the created token in the request header to the backend. How do I use it ？Thank you much。

**Comment by toadkicker** [comment]
In nuxt.config.js add something like this:

```javascript
axios: {
    requestInterceptor: (config, { store }) => {
      config.headers.common['access-token'] = store.state.user.headers.access_token
      config.headers.common['token-type'] = store.state.user.headers.token_type
      config.headers.common['client'] = store.state.user.headers.client
      config.headers.common['expiry'] = store.state.user.headers.expiry
      config.headers.common['uid'] = store.state.user.headers.uid
      return config
    },
    responseInterceptor: (res, ctx) => { }
}
```

Fill it in with your logic

**Comment by pi0** [comment]
For release `5.x` create a plugin `plugins/axios` and do this:

```js
export default function ({ axios, store }) {
 axios.onRequest(() => {
      config.headers.common['access-token'] = store.state.user.headers.access_token
      config.headers.common['token-type'] = store.state.user.headers.token_type
      config.headers.common['client'] = store.state.user.headers.client
      config.headers.common['expiry'] = store.state.user.headers.expiry
      config.headers.common['uid'] = store.state.user.headers.uid
 })
}
```

**Comment by tchret** [comment]
@pi0: 
![image](https://user-images.githubusercontent.com/4539476/37653983-876909bc-2c38-11e8-8f5f-80099fbe2e08.png)

**Comment by pi0** [comment]
@tchret I think you should use `$axios.onRequest`

**Comment by tchret** [comment]
yes, thanks @pi0! 
here is the correct way to do it:

```js
export default function ({ $axios, store }) {
 $axios.onRequest((config) => {
  ...
 })
}

```

**Comment by RobotOptimist** [comment]
I wasn't sure if I could use the setToken helper function from a plugin, so I improvised using the above code and instead of the [access-token] etc headers I used this:

`config.headers.common['Authorization'] = `Bearer ${store.getters['auth/token']}`;`

If there is a better way to do this I would be grateful to know it. Thank you!

**Comment by usb248** [comment]
```javascript
export default function ({ $axios, store }) {
  $axios.onRequest( (config) => {
    if (store.state.token) {
      config.headers.common['Authorization'] = `Bearer ${store.state.token}`
    }
  })
}
```

get error in console : TypeError: $context is null and result Nuxt Server Error

**Comment by cyberz** [comment]
> get error in console : TypeError: $context is null and result Nuxt Server Error.
> Still doesn't work ...

Try to install Axios Module for Nuxt and enable it in nuxt.config.js. 
See more [https://axios.nuxtjs.org/setup](url)

**Comment by toadkicker** [comment]
@usb248 `$context` is null because you aren't adding it in your function params. `function ($context)`. 
You are destructuring context here and grabbing two of its properties (`$axios` and `store`).

See https://nuxtjs.org/api/context#the-context

**Comment by theCrius** [comment]
Following this issue comments' chain, this is my situation:

nuxt.config.js
```
modules: [
    '@nuxtjs/axios',
    ...
},
plugins: [
    '~/plugins/axios',
    ...
```

axios.js - plugin
```
export default function({ $axios, store, redirect }) {
  console.log('AXIOS PLUGIN LOADED');

  $axios.onRequest(request => {
    console.log('[ REQUEST ]' + request.url)
    if (store.state.sessionStorage.authUser) {
      request.headers.common['Authorization'] = store.state.sessionStorage.authUser.token_type + ' ' + store.state.sessionStorage.authUser.access_token;
    }

    return request
  })

  $axios.onResponse(response => {
    console.log('[ RESPONSE ]' + response.request.responseURL, response)
    // TODO: If token expires, perform a silent refresh

    return response
  })

  $axios.onError(error => {
    console.error('[ ERROR ]', error)
    const code = parseInt(error.response && error.response.status)
    if (code === 401) {
      store.state.sessionStorage.authUser = null
      return redirect('/')
    }

    return error
  })
}
```

I see the message `AXIOS PLUGIN LOADED` but the events (onRequest, onResponse, onError) and not being triggered.

What am I missing?

**Comment by ChartWay** [comment]
> Following this issue comments' chain, this is my situation:
> 
> nuxt.config.js
> 
> ```
> modules: [
>     '@nuxtjs/axios',
>     ...
> },
> plugins: [
>     '~/plugins/axios',
>     ...
> ```
> 
> axios.js - plugin
> 
> ```
> export default function({ $axios, store, redirect }) {
>   console.log('AXIOS PLUGIN LOADED');
> 
>   $axios.onRequest(request => {
>     console.log('[ REQUEST ]' + request.url)
>     if (store.state.sessionStorage.authUser) {
>       request.headers.common['Authorization'] = store.state.sessionStorage.authUser.token_type + ' ' + store.state.sessionStorage.authUser.access_token;
>     }
> 
>     return request
>   })
> 
>   $axios.onResponse(response => {
>     console.log('[ RESPONSE ]' + response.request.responseURL, response)
>     // TODO: If token expires, perform a silent refresh
> 
>     return response
>   })
> 
>   $axios.onError(error => {
>     console.error('[ ERROR ]', error)
>     const code = parseInt(error.response && error.response.status)
>     if (code === 401) {
>       store.state.sessionStorage.authUser = null
>       return redirect('/')
>     }
> 
>     return error
>   })
> }
> ```
> 
> I see the message `AXIOS PLUGIN LOADED` but the events (onRequest, onResponse, onError) and not being triggered.
> 
> What am I missing?

Me too..

**Comment by senher** [comment]
I succeeded in this way：
nuxt.config.js
`plugins: [
    '@/plugins/element-ui',
    // '@/plugins/axios',
  ],
modules: [
    '@nuxtjs/axios',
  ],
`
and plugins
`export default function ({ $axios, store }) {
  $axios.onRequest((config) => {
    config.headers.common['user_token'] = `9999999999999`
  })
}
`

**Comment by aliwesome** [comment]
still have this issue.

**Comment by psahni** [comment]
Hello Guys,
You have to use 
```
  this.$axios('your url') to make axios request
```
importing it separately will not fire the interceptor

@aliwesome @ChartWay @theCrius
