### ISSUE TITLE
error when build  with nuxtjs/axios in backpack 

### ISSUE THREAD

**Issue by jrs320** [nuxt-community/axios-module#64]
##Help me please, The problem is ：
![image](https://user-images.githubusercontent.com/6623047/33432014-5ce0be7e-d611-11e7-9d3c-ac6512cb654a.png)

![image](https://user-images.githubusercontent.com/6623047/33432043-7e9b65fa-d611-11e7-9a6e-e903779f4d6c.png)

**Comment by pi0** [comment]
Hi. You just added extra spaces around `:` for baseURL :)

**Comment by jrs320** [comment]
Haha，yes，i see，so little error you also can find, you are my hero，you 666
