### ISSUE TITLE
how to use "timeout" in this module???

### ISSUE THREAD

**Issue by hello-guoguo** [nuxt-community/axios-module#65]
# I'd like use 'timeout' in my project,and how to do???

**Comment by pi0** [comment]
Please provide more details.

**Comment by hecktarzuli** [comment]
I assume this person is wondering how to set the default axios timeout when using this module.  You could do it in a plugin using $axios.defaults.timeout, but I would have assumed you could do it within the nuxt.config.js somewhere, but that doesn't seem to work.

**Comment by cherenkor** [comment]
In the nuxt project simply add it to the plugin/axios.js file inside export function
`$axios.defaults.timeout = timeInMilliseconds`

<img width="451" alt="Снимок экрана 2019-09-03 в 15 26 54" src="https://user-images.githubusercontent.com/21200035/64173149-4ff23880-ce5f-11e9-9ba0-18b532dfbddb.png">
