### ISSUE TITLE
response.body undefined

### ISSUE THREAD

**Issue by lyzs90** [nuxt-community/axios-module#70]
I'm hitting my own endpoint which returns `res.status(500).json({ message: 'Server Error' })`.  i can see the correct response in Chrome devtools network tab. however, on my app i get `Error: Request failed with status code 500`

```javascript
return this.$axios.$get('/...')
  .then(res => {
    console.log(res)
  })
  .catch(err => {
    console.log(err)
  })
```

its the same for all error codes. the only way i can receive a json is with status 200.

am i missing something here? any help would be appreciated!

**Comment by jonnyparris** [comment]
same - I think this stems from axios itself being broken in the latest version: https://github.com/axios/axios/issues/1085

**Comment by anteriovieira** [comment]
Try to get the `response` 

```js
...
.catch(err => {
   console.log(err.response)
})
```

**Comment by lyzs90** [comment]
@anteriovieira that works for me! could have sworn i tried it though

**Comment by pi0** [comment]
Closing as this seems not directly related to this repo.
