### ISSUE TITLE
setToken resets on page refresh

### ISSUE THREAD

**Issue by jonnyparris** [nuxt-community/axios-module#72]
Setting a basic auth header with setToken works great throughout my app...unless the page refreshes and I get 401 errors.
Am I doing something wrong or is this a bug?

In my login component:
```javascript
methods: {
    async login() {
      sessionStorage.setItem('loginUsername', this.loginUsername);
      sessionStorage.setItem('loginPassword', this.loginPassword);
      const credsString = this.loginUsername + ':' + this.loginPassword;
      const encodedCreds = window.btoa(credsString);
      this.$axios.setToken(encodedCreds, 'Basic');
      ...
```

...then in my vuex stores and modules, I'm referencing axios as `this.$axios` as per the docs.
Any help much appreciated!

**Comment by pi0** [comment]
Hi bro. Actually, this is an expected behavior. Also, consider that if you need to make SSR requests (In asyncData or ...) localStorage is not enough and cookies are needed.
