### ISSUE TITLE
Can't get response headers

### ISSUE THREAD

**Issue by mclighter** [nuxt-community/axios-module#73]
I tried to get headers from response, but i dont know how i can do it 
data contains only body

```javascript
async created () {
        const data= await 
        this.$axios.$get('posts')
        this.posts = data
      }```

**Comment by anteriovieira** [comment]
`$get` is just a helper, you can use  `get` native

```js
async created() {
  const response = await this.$axios.get('posts')
  this.posts = response.data
}
```

**Comment by mclighter** [comment]
Thanx! 
`this.headers = response.headers `
it worked,
in my case(cross domain),  not all needed headers were in response
but this is server side problem, i fixed it by adding this code on backend
"Access-Control-Expose-Headers" = ['X-Pagination-Current-Page','X-Pagination-Total-Count'],

**Comment by kristinadinellari** [comment]
@anteriovieira I can't get headers of response in the client-side , I can get headers only on server-side do you have any idea where I can config to display them and on client-side response as well ????

**Comment by mitrikovsky** [comment]
I have the same problem as for @kristinadinellari
I can get all headers on SSR but on the client side there is only 'Content-Type' but I need 'X-Pagination-Current-Page', 'X-Pagination-Total-Count' as well
Does anyone have a clue?

**Comment by mitrikovsky** [comment]
My bad. Actually on backend `"Access-Control-Expose-Headers" `from previous answer solves the problem for client-side as well:
`"Access-Control-Expose-Headers" = ['X-Pagination-Current-Page','X-Pagination-Total-Count']`
All headers passed here appeared in axios response
