### ISSUE TITLE
Getting 404 error as it's adding multiple /api paths

### ISSUE THREAD

**Issue by dan-gamble** [nuxt-community/axios-module#74]
I have a simple call:

```javascriot
  export default {
    async asyncData({ app }) {
      const nations = await app.$axios.$get('/api/nations')
      console.log(nations)
    }
  }
```

I've used a combination of:

```javascript
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/proxy'
  ],

  axios: {
    baseUrl: 'http://localhost:8000'
  },

  proxy: {
    '/api': { target: 'http://localhost:8000/api', pathRewrite: { '^/api': '' } }
  }
```

And for some reason it always call `http://localhost:8000/api/api/nations`. I've been tearing my hair out over this as i'm pretty sure it's just something simple i'm missing.

**Comment by pi0** [comment]
Hi. This is simply because axios base url is set to `/api` [by default](https://github.com/nuxt-community/axios-module#baseurl). So what you want is making requests like this:
```js
const nations = await app.$axios.$get('nations')
```

**Comment by dan-gamble** [comment]
Thanks! :) Is it possible to remove the `/api` by default?

**Comment by pi0** [comment]
Sure. Just set baseURL to `/`: 

```js
 axios: {
    baseUrl: '/'
  },
```

**Comment by dan-gamble** [comment]
That still seems to do `/api/api/nations` for me. But i think i'll just stick with you're initial answer as that still works, just takes a bit of getting used to :)

**Comment by pi0** [comment]
@dan-gamble Your welcome and apologizes for hard config process. Many of my coworkers reported such problems. We should rethink about a complete rewrite with built-in proxy support and easier usage. Any comments welcome :)

**Comment by dan-gamble** [comment]
It's no worries, thanks for your quick help :)

I think for me personally, by default it trying to think what i'm going to do sounds nice on paper but on reality makes config a tad harder (Initially it was doing `/api/api/api/nations/` for me :D). I like to be able to write `app.$axios.$get('/api/nations')` by default then over time if i feel like it makes sense for me to add the `baseUrl` as `api/` as an option down the line.

Built in proxy support would be awesome, i imagine a big use case of Nuxt is pairing it with an API :)

**Comment by husayt** [comment]
Hi @pi0, I am also really struggling to understand the configuration. In my setup I have axios working with proxy. I need to make calls to 3rd party server through proxy. How do i do that?

I hav nuxt/axios with nuxt/proxy
Let's say the url is "http://datasrvr:8888/data/items"
nuxt config looks like this:

```
modules: [
    '@nuxtjs/axios',
    ['@nuxtjs/proxy', {
      logLevel: "debug",
      ws: false,
      changeOrigin: true,    
    }],
  axios: {
    debug: true,
    baseURL: `http://localhost:3000`,
  },
  proxy: {
    "/data": { target: "http://datasrvr:8888", pathRewrite: { '^/data': '' },  changeOrigin: false}
  },
```

Then calling "http://localhost:3000/data/items" works.
I have the page "http://localhost:3000/workitems" where I call the above url with axios. That works on client-side, but with ssr it fails with 404.

I have spent 2 days trying to find right configuration for axios and proxy. What am I missing?

**Comment by pi0** [comment]
A new RC is going to be released soon with hopefully more clean API.

**Comment by husayt** [comment]
That would be great, but what can I do meanwhile for the above issue? I spent whole day trying to get it work. Any help would be really appreciated

**Comment by pi0** [comment]
@dan-gamble Thanks for your suggestion. Release 5.0.0 is almost ready with a much more clean API.

@husayt Sorry for the delay. We have now built-in proxy support. (Please see the docs).

Should work with this config:

```js
{
   modules: [
    '@nuxtjs/axios'
  ],

  axios: {
    debug: true,
    proxy: true,
  },

  proxy: {
    "/data": { target: "http://datasrvr:8888", pathRewrite: { '^/data': '' } }
  }
}
```

If still having problems, please open a new Issue with a reproduction example and mention me. I will help you as fast i can :)

**Comment by husayt** [comment]
Pooya, thank you very much for the example. Since you have a builtin proxy,
do we still need to include @nuxt/proxy?

**Comment by pi0** [comment]
@husayt Your welcome. No we don't :)

**Comment by pi0** [comment]
It still uses the same module. But with a better and more unified configuration.

**Comment by husayt** [comment]
Pooya I created a new ticket per your advice #82. Also,

>@husayt Your welcome. No we don't :)

I had to add nuxt/proxy to package.json, for it to work.
