### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by robsontenorio** [nuxt-community/axios-module#75]
So... wont work :(

```
methods: {
  async fetchSomething() {
    const ip = await this.$axios.$get('http://icanhazip.com')
    this.ip = ip
  }
}
```

**Comment by robsontenorio** [comment]
I can do it by 

```
const ip = await this["$axios"].$get("http://icanhazip.com");
```

But i dont think it is a elegant solution.

**Comment by pi0** [comment]
Hi. Would you please provide more details? I mean why typeScript doesn't support `$` prefixed function? If possible please provide a repro example and reopen the issue. I would be happy to help to resolve this.
