### ISSUE TITLE
axios auto retry on failed requests (timeout, 500,...)

### ISSUE THREAD

**Issue by simllll** [nuxt-community/axios-module#77]
Are there any ideas or plans to retry failed requests automatically? I've seen it serveral times especially on mobile users that from time to time requests just fail. Or there are some temporary 500er due to server scalings or whatever.

There is e.g. exios-retry out there:
https://www.npmjs.com/package/axios-retry

Would be nice to have thisin this module, retrying of 500er or timeouts with a exponential backoff strategy.

Let me know what you think about it, I can implement it otherwise.

Thanks
Simon

**Comment by pi0** [comment]
Will be available soon 🍷 Thanks for the suggestion.
