### ISSUE TITLE
redirectError not work(4.5.2)!!

### ISSUE THREAD

**Issue by Harveyzhao** [nuxt-community/axios-module#78]
Hello, when i upgrade this plugin to 4.5.2,it's not work~~
But I back to 3.1.0, it can work. (the version is my first time used)

**Comment by Harveyzhao** [comment]
![wechatimg303](https://user-images.githubusercontent.com/15974393/35030553-4e4ae818-fb9a-11e7-82be-9b5284540636.jpeg)
I must add 'disableDefaultErrorHandler: false,'(Default is false?) ,and remove errorHandler function,'redirectError' is working.
And another way , I only use 'errorHandler' and do redirect inside it, it also can work. 

the source code  `<% } else if (options.disableDefaultErrorHandler === false) { %>` maybe not work when I don't set disableDefaultErrorHandler to false ~

**Comment by pi0** [comment]
Hi. With release `5.0.0` you have to use a plugin to manually handle error/redirects. 

Please see [Extending Axios](https://github.com/nuxt-community/axios-module#extending-axios) section.

Also please make sure to read [Migration Guide](https://github.com/nuxt-community/axios-module/wiki/Migration-Guide).

If any problem exists, feel free opening a **new issue**.
