### ISSUE TITLE
Property $axios is unavailable from vuex actions

### ISSUE THREAD

**Issue by icehaunter** [nuxt-community/axios-module#79]
When using the plugin, according to docs, one should be able to call `$axios` property from `this` in vuex store actions. This is not the case, as it does not get injected for some reason: neither `this` nor `context` have `$axios` (or `axios`) property.

The test action looks like this: 
```javascript
testUpdate: async (ctx) => {
    console.log(ctx) // No $axios
    console.log(this) // No $axios
    return this.$axios.$get('/graphql')  // "$axios is not a function"
  }
```
`$axios` is properly injected on components and `this.$store`.
I am using vuex in modules mode with nuxt as per docs

Versions:
```
nuxt: 1.1.1
vue: 2.5.13
vuex: 3.0.1
nuxtjs/axios: 4.5.2
```

**Comment by pi0** [comment]
Hi. This is because arrow functions don't support bounding to context (`this`). Please try this:

```js
async testUpdate(ctx) {
    console.log(ctx) // No $axios
    console.log(this) // No $axios
    return this.$axios.$get('/graphql')  // "$axios is not a function"
  }
```

**Comment by icehaunter** [comment]
Wow, @pi0, thanks, gotten so used to writing actions with arrow functions that forgot they rebind `this`. Thanks a lot, don't know how I've missed this!

**Comment by danjac** [comment]
I'm still seeing this issue (nuxtjs/axios 5.3.1).

nuxt.config.js:
`....
  modules: [
    '@nuxtjs/axios',
  ],
`
Store:

`
  actions: {
    nuxtServerInit ({ commit }, { req, app }) {
      console.log('axios?', app.$axios) // axios is undefined
      if (req.session && req.session.user) {
        commit('SET_USER', req.session.user)
      }
    },
    async login ({ commit }, creds) {
      try {
        // throws TypeError this.$axios is undefined
        const response = await this.$axios.$post('/auth/login/', creds)
        commit('SET_USER', response.data)
      } catch (e) {
        console.log('error', e)
        commit('SET_USER', null)
      }
    },
`
$axios is unavailable both in nuxtServerInit app instance and all other actions. Not using arrow functions (this.app for example is available). Looks like either the docs or the code is broken.

**Comment by hoanghiep1x0** [comment]
If someone intends to call axios, call it via dispatch

`` `
   export const actions = {
     // nuxt server Init only works on store / init
     async nuxtServerInit ({dispatch}) {
         let response = await dispatch ('member / list', {page: 1});
         console.log (response);
       }
}
`` `

module file member.js

`` `
   async list ({commit}, payload) {
         return await this. $ axios. $ post ('/ user / list', payload) .then ((response) => {
             commit ('fetchSuccess', response);
             return response;
             })
             .catch (error => {
                 return error.response.data;
             });
     },
`` `

Sorry if the answer is not appropriate but someone will need to hope that this explains them

**Comment by yedincisenol** [comment]
@danjac try this,
`` 
    login: async function ({ commit }, creds) {
      try {
        const response = await this.$axios.$post('/auth/login/', creds)
        commit('SET_USER', response.data)
      } catch (e) {
        console.log('error', e)
        commit('SET_USER', null)
      }
    },
``

**Comment by slidenerd** [comment]
@danjac how do you get acess to req.session inside the async login method? context.req is null there obviously and axios response doesnt contain cookies
