### ISSUE TITLE
Provide simple cache option

### ISSUE THREAD

**Issue by homerjam** [nuxt-community/axios-module#8]
It'd be great to be able to easily add caching - I found one suggestion [here](https://github.com/nuxt/nuxt.js/issues/1274), which is to use [cachios](https://github.com/AlbinoDrought/cachios) on a proxied api. However it'd be my preference to use [lru-cache](https://github.com/isaacs/node-lru-cache) instead.

**Comment by homerjam** [comment]
[This](https://gist.github.com/homerjam/933336f19ff1302e7a8dd2c6784dd172) is what I'm using for now, can anyone suggest if/how this could be integrated?

**Comment by mheppner** [comment]
Just as an FYI, this is being planned for the 1.x release of axios itself. Maybe there should be some collaboration to get this off the ground. See mzabriskie/axios#206, specifically tracked in issue 31.

**Comment by homerjam** [comment]
Interesting, though it looks like the discussion resolved to leaving it up to the user to implement via interceptors. Is there an argument that as this module already decorates axios with best practices for nuxt, caching could be one of them?

**Comment by mheppner** [comment]
I don't think I'm qualified to answer whether or not it should be implemented here, but I just wanted to make everyone aware that the feature is being planned for the upstream module. With that being said though, the author's proposed caching package has been dead for over a year, and the issue tracking the feature, originally opened in 2014, has been closed and not much activity has been added since then. It'd definitely be nice if this nuxt module could implement it, then port some of it back over to axios.

**Comment by pi0** [comment]
@mheppner I'm totally up with this enhancement if we can add it as an opt-in option for axios module. But something important to mention, is we need to **prevent sharing cache between SSR requests** or maybe just use it for client side only. Caching stateful requests would introduce new security risks as well.

Also with [workbox](https://github.com/nuxt-community/modules/tree/master/modules/workbox) or [pwa](https://github.com/nuxt-community/modules/tree/master/modules/pwa) module, an standard service worker just does the same, transparently caching All XHR requests (including ones using axios) with less security risks :)

**Comment by mheppner** [comment]
@pi0 I honestly didn't know that about service workers, sorry! That would just be frontend caching, though, right?

**Comment by homerjam** [comment]
Service workers are frontend only, I've used them in the past but found they can introduce complexity. How do you invalidate a client's cache for example?

Not sure I understand enough to know the security risks, or indeed what exactly constitutes a stateful request. Also what would be the issue with sharing the cache between ssr requests? Genuine question as I think that's exactly what I'm doing!

Opt-in cache ftw.

**Comment by homerjam** [comment]
Hey @pi0, any idea if it might be possible to use the `adapter` option as [this plugin](https://github.com/kuitos/axios-extensions) does?

**Comment by pi0** [comment]
`opt-in` cache should be happening as a `serverMiddleware` (or in API / Reverse proxy / Nuxt Proxy).  I've checked both [axios-extensions](https://github.com/kuitos/axios-extensions) and [cachios]. Both are just using a simple and blind LRU cache which is something useful for server-side only. Still, if you think it is a good approach we can add any interceptor and custom adapter by [extending axios](https://github.com/nuxt-community/axios-module#extending-axios).

Summary:

- For browser caching: service workers provide a high quality caching mechanism
- For server side: We can add such feature to [proxy module](https://github.com/nuxt-community/proxy-module) . PRs welcome :)
