### ISSUE TITLE
version 4.5.2 causes ~383KB increase in vendor.js

### ISSUE THREAD

**Issue by simap** [nuxt-community/axios-module#81]
I tracked down a large chunk of my vendor.js file size down to this module. 
Removing 4.5.2 and using the current code helps significantly, so the probably is likely already fixed, but not yet released.
It looks like the whatwg module (now removed) pulls in a bunch of things that bloat it. Most of it shows up in tr46 module using `nuxt build -a`

**Comment by pi0** [comment]
Hi. `5.0.0-alpha.0` is released which should hopefully resolve this problem. Be use to read [Migration Guide](https://github.com/nuxt-community/axios-module/wiki/Migration-Guide) before upgrading.

**Comment by simap** [comment]
Thanks!
