### ISSUE TITLE
Performing multiple concurrent requests (.all) is not defined

### ISSUE THREAD

**Issue by epartipilo** [nuxt-community/axios-module#9]
Hi, I'm trying to use the _Performing multiple concurrent requests_ from axios, is it going to be available?
```
    const res = await app.axios.all([
        app.axios.$get('/api/brand', {params: {all: true}}),
        app.axios.$get('/api/model', {params: {all: true}})
    ])
```

Thanks!

**Comment by pi0** [comment]
Hi @epartipilo . Please see: https://github.com/nuxt-community/modules/issues/40

**Comment by pi0** [comment]
Hi @epartipilo . Please see https://github.com/nuxt-community/modules/issues/55
