### ISSUE TITLE
How to use @nuxtjs/axios in page vue

### ISSUE THREAD

**Issue by arvindkumarbadwal** [nuxt-community/axios-module#90]
How can i access axios in index vue page or any other page.

`export default {`
` asyncData({params, app }) {`
` return app.$axios.get("http://localhost:4000/todos").then(res => {`
`      return { posts: res.data.slice(0, 5) };`
`    });`
`  }`

and also give an example how to use @nuxtjs/axios in default nuxtjs project.

**Comment by pi0** [comment]
Hi. You can even do it more easily: (Using `$get` helper)

```js
export default {
  async asyncData({params, app }) {
    const items = await app.$axios.$get("http://localhost:4000/todos")
    return { posts: items.slice(0, 5) }
  });
}
```

**Comment by pi0** [comment]
Also, docs describe more examples. If still having problems feel free reopening this issue with your exact question i would be happy to help.
