### ISSUE TITLE
Question on setting token with onRequest

### ISSUE THREAD

**Issue by easteregg** [nuxt-community/axios-module#92]
I couldn't get `$axios.setToken`  to work with `$axios.onRequest`. I don't know what I am doing wrong. 
I followed the instructions on [readme](https://github.com/nuxt-community/axios-module#interceptors) and added `$axios.setToken(token, 'bearer')` in `onRequest` method. Unfortunately no token were added. 

But when I do it inside the plugin (~/plugins/axios.js): 

```
export default function ({$axios, store}) {
  let token = store.getters['auth/token']
  $axios.setToken(token, 'Bearer')
}
```

Without the `$axios.onRequest` method. It attaches the token to the request. this feels wrong to me, would you please help me figure this thing out?

**Comment by pi0** [comment]
Hi. The `setToken` helper actually globally sets token for all requests and should be called once. You should watch store state and update token each time it is changed using `this.$axios.setToken`. For a better auth experience, i suggest using [auth-module](https://github.com/nuxt-community/auth-module).

**Comment by easteregg** [comment]
Thank you @pi0,

I guess my mindset was wrong. I was trying to upgrade from a previous version of `@axios-module` and there was interceptors back in the  day, blah blah. Anyway l will definitely check out the module you've suggested. Keep up the awesome work. :)
