### ISSUE TITLE
$axios is not available

### ISSUE THREAD

**Issue by NeOMakinG** [nuxt-community/axios-module#94]
Hello guys,

Looks like axios it not imported when he's added in nuxt.config.js, auth-module is returning me $axios is not available even if axios is before auth in the module array..

Thanks for your help !

**Comment by NeOMakinG** [comment]
You still need to add axios after auth in the doc...

Fixed

**Comment by pi0** [comment]
Hi. Closing as a dup of nuxt-community/auth-module#56
