### ISSUE TITLE
[Question] Using localhost for development and domain name in production

### ISSUE THREAD

**Issue by lsbyerley** [nuxt-community/axios-module#95]
I am running nuxt programmatically on an express server. My local dev environment and api is running on localhost:3000. I have the typical nginx reverse proxy setup pointing to this port in production. 

In production, on inital page load, everything loads fine since its rendered server side. If I click on another page that requires an api request, I see the request going to `localhost:3000/api/**` instead of `mydomain.com/api/**`

What would be the proper way to set this up in nuxt.config.js file so that the local dev build points to localhost and when I run build in production it sets the baseUrl to my domain name?

**Comment by pi0** [comment]
Hi. If you are running both on the same server, you have two ways:

1. Just set `proxy: true` option. (This won't actually use proxy but makes requests going to a relative path) 

2. During production build, set environment variable `API_URL` something like this:

```bash
API_URL=http://mydomain.com yarn build
```

**Comment by lsbyerley** [comment]
@pi0 Thank you! Option 1 works great.

**Comment by jfcmoeller** [comment]
@pi0 thank you. Where do I have to set proxy to true? In the axios module?
